### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by gschneider-r7** [dask/s3fs#100]
Is there a regular release schedule for this project, or some planned milestone for upcoming releases? It would be nice to have a rough idea for when a new version might be published.

For context I am interested in the fix from #98. For now I am specifying the git repo in my requirements file so I'm not blocked nor in a particular hurry.

**Comment by martindurant** [comment]
There is no specific schedule - I'll try to do it tomorrow!

**Comment by martindurant** [comment]
Now on conda-forge
