### ISSUE TITLE
Walk method doesn't match python standard lib interface

### ISSUE THREAD

**Issue by jcrist** [dask/s3fs#107]
The implementation of walk in `s3fs` returns a flat list of all paths encountered when traversing the tree. In contrast, `os.walk` from the standard library returns an iterator of `dirname, dirs, files`, where `dirname` is the current directory prefix in the traversal, and `fils` and `dirs` are the names (relative, not absolute) of all files and directories respectively.

This difference in behavior is confusing for those familiar with the standard `os.walk` method, and also makes providing the interface used by `pyarrow` (which does match the standard library) tricky.

Pyarrow has created a wrapper class that provides the proper method interface, see [here](https://github.com/apache/arrow/blob/master/python/pyarrow/filesystem.py#L319-L349). Is there any reason not to just upstream this? We'd potentially need to figure out a good deprecation path, as the current behavior *may* be used by users.

**Comment by samkennerly** [comment]
I use (and vastly prefer!) the flat list returned by `S3FileSystem.walk`. That said, @jcrist is right: it's different from `os.walk`, and the difference was confusing.

Making `walk` more like `os.walk` would break my current code, but I'm OK with that. It's an easy fix, and I should rewrite it anyway to avoid any possible clash with `pyarrow`, which I also use heavily.

Does anyone here know how many others would be affected by changing `walk`? In the docs, it's in the [S3FileSystem summary](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem) but not the [API summary](https://s3fs.readthedocs.io/en/latest/api.html#api).

**Comment by martindurant** [comment]
In filesystem_spec, I am proposing making walk match the python API, but provide find, which retains the current behaviour (list of paths), similar to the posix `find` command without the templates. Templates could be added later...

**Comment by samkennerly** [comment]
That sounds good to me. All I really need is something like posix `find * -type f`, but for an S3 bucket.

**Comment by martindurant** [comment]
Implemented in fsspec
