### ISSUE TITLE
Add methods to set/get tags for S3File similar to metadata

### ISSUE THREAD

**Issue by kinzleb** [dask/s3fs#113]
Boto3 now allows us to tag s3 objects with key/value pairs.  These don't have some of the limitations that storing things in metadata have like requiring us to rewrite the file in s3 just to update the metadata which is problematic for large files.

http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_object_tagging
http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.get_object_tagging

Here are some of the limitations of tagging:
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html

**Comment by martindurant** [comment]
Sounds like a reasonable request. Do you see this being 
- an additional pair of methods alongside the existing xattr ones, 
- replacing/superseding them, or 
- both mechanisms being available from the same methods, with either an optional keyword or an instance-level config?

Do you have any interest in making this PR?
Do you know if `moto` (the mocking server used for testing) supports tags?

**Comment by mariusvniekerk** [comment]
`x_object_tagging` seems to be supported in moto according to https://github.com/spulec/moto/blob/770281aef2132de8b4d8abb7ec3325a3038b6f09/tests/test_s3/test_s3.py#L1990

**Comment by kinzleb** [comment]
@martindurant I'd see it as "an additional pair of methods alongside the existing xattr ones".  I'm certainly willing to attempt this -- I'm no expert when it comes to python coding design principals or in creating the tests to go along with this though.

**Comment by martindurant** [comment]
@kinzleb , I plan to get this done before the start of next week, unless you beat me to it, as s3fs is overdue a release.

**Comment by kinzleb** [comment]
@martindurant Sounds like you'll get to it before me then -- as much as I'd like to contribute, probably a good thing as I still have a lot to learn about contributing to these projects.
