### ISSUE TITLE
Migrate performance improvements from GCSFS

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#116]
There has been a fair amount of use of gcsfs recently on large datasets.  This exposed several performance bottlenecks that were subsequently fixed.  Are some of these performance bottlenecks likely to occur on s3fs as well?  Are there performance improvements that we should take care to migrate over?

**Comment by martindurant** [comment]
The major part, using directory prefixes, is already implemented on s3fs, so I am not aware of any performance problems that people are experiencing. There is no FUSE implementation in s3fs, but maybe there are people out there using other s3/fuse libraries?

An explicit benchmark of s3fs versus gcsfs for a specific use-case (say zarr storage) has not been done, but perhaps should be. That would depend on a number of variables, of course, such as which compute infrastructure was being used.
