### ISSUE TITLE
ClientErrors should bubble up to callers

### ISSUE THREAD

**Issue by wrobstory** [dask/s3fs#118]
Hi dask friends!

I spent a frustrating bit of time trying to figure out why s3fs was not able to find files in a bucket where I was sure they actually lived. After some digging I realized that when listing the contents of a bucket, `ClientError`s are swallowed and the contents of the bucket returned as empty: https://github.com/dask/s3fs/blob/master/s3fs/core.py#L320

What do you all think about letting that error bubble up to callers? I think this would be a friendlier user experience for people trying to sort out bucket permissions, etc.

**Comment by mrocklin** [comment]
@martindurant any thoughts on this?

(Hi @wrobstory !  sorry for the delay!)

**Comment by martindurant** [comment]
I don't have a string feeling on this. There are many possible permissions patterns within a bucket structure, and aborting an operation when some part fails seems like a bad idea (see other issues from cases where the user cannot, for instance, list buckets at all). Perhaps warnings could be a nice middle-ground?

**Comment by TomAugspurger** [comment]
Correct me if I'm wrong, but @wrobstory was proposing that the error be re-raised if and only if all the checks failed with a client error? If any files are successfully discovered, there's on change. If no files are discovered because there really aren't any files in that prefix then nothing changes. Just the case where it's all ClientErrors?

**Comment by wrobstory** [comment]
^^^ thats correct. I think there are two ways to go here: 

1. Show a warning if you run into any part of the bucket where you don't have permissions
2. Only raise an error if you run into permissions errors for _every_ bucket action you try to take. 

tbh the former actually seems like a pretty good solution to me. I just wanted some sort of indication that I was actually having permissions errors, not an empty bucket. 

(hi @mrocklin!)
