### ISSUE TITLE
Dots (.) in glob

### ISSUE THREAD

**Issue by zhangwen0411** [dask/s3fs#122]
`glob` doesn't seem to be dealing with dots (`.`) correctly:
```python3
>>> from s3fs import S3FileSystem
>>> s3 = S3FileSystem()
>>> s3.ls("s3fs-glob-test")
['s3fs-glob-test/ab.txt']
>>> s3.glob("s3fs-glob-test/a.*.txt")
['s3fs-glob-test/ab.txt']
```
The path is returned even though `ab.txt` shouldn't match the pattern `a.*.txt`.

**Comment by martindurant** [comment]
Thanks for the example.
The glob logic is implemented using regular expressions, in which `'.'` is a wildcard. Clearly a little refinement could be done. Are you interested in providing a PR?
