### ISSUE TITLE
* not working in glob

### ISSUE THREAD

**Issue by cscetbon** [dask/s3fs#125]
`glob` raises an exception when I try to use a simple asterisk on the latest version :

In [5]: storage.glob('bucketx/a')
Out[5]: ['bucketx/a/b']

In [6]: storage.walk('bucketx/')
Out[6]: ['bucketx/a/b/c/d/sh']

In [7]: storage.glob('bucketx/*/b')
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
...
~/.virtualenvs/cassie-backup/lib/python3.6/site-packages/s3fs/core.py in info(self, path, **kwargs)
    411         except (ClientError, ParamValidationError) as e:
    412             logger.debug("Failed to head path %s", path, exc_info=True)
--> 413             raise FileNotFoundError(path)
    414
    415     _metadata_cache = {}

FileNotFoundError: bucketx/*/b

**Comment by martindurant** [comment]
Is 'bucketx/a/b' a key?

**Comment by cscetbon** [comment]
You can see in my precedent post that it's a folder not a key

```
In [6]: storage.walk('bucketx/')
Out[6]: ['bucketx/a/b/c/d/sh']
```

**Comment by martindurant** [comment]
Glob is only supposed to find files. In fact, the first call has the incorrect result.

**Comment by cscetbon** [comment]
but why ? `glob` should return whatever is in there, folders or keys like the `glob.glob` :

```
In [13]: glob.glob('/usr/local/var/lib/cassandra/data/k1/*/snapshots/my-tag')
Out[13]: ['/usr/local/var/lib/cassandra/data/k1/t1-836b19b03ebf11e8994f0bab9605c867/snapshots/my-tag']

In [14]: glob.glob('/usr/local/var/lib/cassandra/data/k1/*/snapshots/my-tag/*')[:2]
Out[14]:
['/usr/local/var/lib/cassandra/data/k1/t1-836b19b03ebf11e8994f0bab9605c867/snapshots/my-tag/k1-t1-ka-1-CompressionInfo.db',
 '/usr/local/var/lib/cassandra/data/k1/t1-836b19b03ebf11e8994f0bab9605c867/snapshots/my-tag/k1-t1-ka-1-Data.db']
```

**Comment by martindurant** [comment]
There are no real directories on S3, the library jumps through a lot of hoops to get ls working. `glob` is implemented by filtering the output of `walk`, which only returns files as expected.

**Comment by cscetbon** [comment]
I see no blocker to implement it. If we want to work with s3 as we do with files and directories it makes sense to me. I need to find paths that contain a certain folder without having to know exactly what's stored in deeper levels. A workaround would be to use walk and then apply a regex on it what is done internally, something which can be done with the regular `glob.glob`.

I don't think it would be hard to implement. We could also limit the walk when the end of the pattern is reached (avoiding to walk through deeper level when we're only interested in folders)

**Comment by martindurant** [comment]
Would you like to have a go? 
I recommend by starting with `S3FileSystem._walk`, adding an optional parameter `dictionaries=False`, and changing the last line of the function appropriately. The same parameter should then appear in `walk`, and so when glob calls it, you get both files and directories.

**Comment by cscetbon** [comment]
Here it is https://github.com/dask/s3fs/pull/126
