### ISSUE TITLE
Improper wildcards handling

### ISSUE THREAD

**Issue by michcio1234** [dask/s3fs#138]
Consider following script:
```
import s3fs
import moto
import boto3

mock = moto.mock_s3()
mock.start()

conn = boto3.resource('s3', region_name='us-east-1')
conn.create_bucket(Bucket='glob-bug')

fs = s3fs.S3FileSystem()

fs.touch('s3://glob-bug/myfile.backup')

print(fs.glob('s3://glob-bug/myfile*'))  # --> ['glob-bug/myfile.backup'] (CORRECT)
print(fs.glob('s3://glob-bug/*myfile'))  # --> ['glob-bug/myfile'] (INCORRECT)

mock.stop()
```
I'd expect that the second `glob` call will return an empty list.

You can also test it on real s3 with (the bucket contains only one file, `myfile.backup`):
```
import s3fs

fs = s3fs.S3FileSystem()

print(fs.glob('s3://michcio1234/glob-bug/myfile*'))
print(fs.glob('s3://michcio1234/glob-bug/*myfile'))
```
I'm using s3fs version 1.5.

**Comment by martindurant** [comment]
Whoa, unexpected!
Thanks for finding and reporting this.
I guess the [regex](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L690) ought to have an end-of-string character `'$'`?

A more thorough implementation of this functionality is in [hdfs3](https://github.com/dask/hdfs3/blob/master/hdfs3/core.py#L349), may be worthwhile duplicating here, although I am in general favour of defining these things [only once](https://github.com/martindurant/filesystem_spec).

**Comment by flixr** [comment]
This would need a bit more rework, simply adding `$` or even `(/|$)` doesn't quite do the trick as then other cases fail...

**Comment by martindurant** [comment]
I wonder, does the version in [fsspec](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py#L369) have the right behaviour, or does it fail in the same way?

**Comment by flixr** [comment]
I didn't explicitly check that, but I don't think so... since it treats/lists files and directories separately...
If I see it correctly in fsspec/hdfs3 walk returns directories separately, in s3fs this is not the case...
