### ISSUE TITLE
Allow users to provide a botocore session on creation of S3FileSystem

### ISSUE THREAD

**Issue by mfulleratlassian** [dask/s3fs#142]
Currently the code creates botocore.session.Session objects during execution. We have reasons that we would like to provide S3FileSystem the session that is to be used (see: https://pypi.org/project/boto3_extensions/  RefreshableAssumeRoleProvider) . I will raise a PR that allows you to pass in a session object and S3FileSystem will use this session for the life of its execution instead of making new sessions.

**Comment by jrbourbeau** [comment]
Closing as passing a session to `S3FileSystem` was added in #143. Thanks @mfulleratlassian!
