### ISSUE TITLE
Set timeout on read operations

### ISSUE THREAD

**Issue by bjorn-spire** [dask/s3fs#146]
I've been working on streaming files from S3 and was looking at how to do it with pure boto3 until I discovered this great library that ended up solving it the same way I was about to write myself, thanks for saving me that time! :D 

One thing I noticed though is that there isn't a timeout set on the `read` on the boto response, which potentially can leave the `read` hanging if there isn't a clear disconnect from the network. I think it'd be a good idea to set a default timeout on that `read` just in case.

The [StreamingBody](https://github.com/boto/botocore/blob/dbd74329c047cfcec9a7d4966b210ae0ae34dd2d/botocore/response.py#L48-L69) object that boto3 returns support setting a timeout so I would suggest changing the code to use it, from what I can tell timeouts are otherwise being caught, and retries are done.

https://github.com/dask/s3fs/blob/daf4bcf47b1b5cf1fde8eb3b9dfaa89b4412af95/s3fs/core.py#L1493-L1497

So introducing another argument to the helper to allow for a read timeout:
```py
            resp = client.get_object(Bucket=bucket, Key=key,
                                     Range='bytes=%i-%i' % (start, end - 1),
                                     **kwargs)
            resp['Body'].set_socket_timeout(read_timeout)
            return resp['Body'].read()
```

I would be happy to whip up a PR for this; I figured it'd be better to ask what you think about this before I went through the work, especially because I'm not entirely sure how to target this particular scenario by a test…

**Comment by martindurant** [comment]
I agree with you in principle, but I am surprised if there isn't a config option for this in the session or client arguments. Have you checked there?

**Comment by bjorn-spire** [comment]
It was the only one I found when I was digging around for it, but I'll take another dive tomorrow and see what I find! :)

**Comment by bjorn-spire** [comment]
The tomorrow came, and I forgot to update here :)

Digging around I found that there is a timeout set in the bowels of boto3 and this suggested change isn't required. 

Thanks for asking me to dig deeper and some software that has been working excellently!
