### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by adamchainz** [dask/s3fs#147]
I'm upgrading from 0.1.5 to 0.1.6 and I can't find any information on what changed in the release. Is it somewhere I'm missing? If not, it would be a nice improvement to publish a changelog file, so if you ever need to make breaking changes they are well publicised.

Thanks for a great library.

**Comment by martindurant** [comment]
You have a point.
However, the commit history is probably the canonical source, and it doesn't include much beyond small bug-fixes in that time. It would be reasonable to start a Changelog page in the documentation, and you are welcome to do so. New contributors should then be encouraged to update it for every PR.
