### ISSUE TITLE
Broken support for python 3.4

### ISSUE THREAD

**Issue by williamrubens** [dask/s3fs#148]
Just out of interest, is there a reason s3fs dropped support for python 3.4 in the latest release? Amazon EMR still uses python 3.4 as the installed python, so the latest version of s3fs is no longer supported by default.

**Comment by martindurant** [comment]
Is there something that doesn't work on py34? s3fs is actually pure-python, so it should run on any version more-or-less; it's just not tested on py34 any more. Since py37 is now out, the usage of 34 must surely drop to about zero very soon.

**Comment by williamrubens** [comment]
well, if you pip-3.4 install s3fs then it fails because setup.py requires version 3.5 or higher

**Comment by martindurant** [comment]
I see what you mean. This reflect lack of testing. I'd be happy to revert the selector, but would you like to close the repo and see if the tests do work?

**Comment by martindurant** [comment]
Done https://github.com/dask/s3fs/commit/69400964b702fa2449454184f1dff62bd7fd36a6

**Comment by williamrubens** [comment]
Thanks!
