### ISSUE TITLE
Reference to `cp` in documentation

### ISSUE THREAD

**Issue by danodonovan** [dask/s3fs#157]
This is possibly a little too picky, but the documenation blurb often makes reference to a `cp` function ([example](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L102)).

However, the `S3FileSystem` implements a `get` function in place of `cp`. Might it be clearer to replace references to `cp` with `get` - or even add a dummy `cp` that implements `get`? 

If a correction is desirable I'll happily push a PR :-)

**Comment by danodonovan** [comment]
Forgive me for being daft, how do you propose we implement `cp` (or `copy`) with the current API? For clarity, I would expect behaviour like AWS CLI `cp`: https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

> Copies a local file or S3 object to another location locally or in S3.

... without streaming data to a local machine and then back up to AWS

**Comment by martindurant** [comment]
There are three methods, `copy` which duplicates a remote file (without streaming locally) and `get`, `put` which do remote-local-remote. We do not have a single method which attempts to determine whether you meant a local or remote file in each path given.

fsspec would give the opportunity to implement a general cp along the lines of AWS's, streaming locally when copying across file-systems, or using whatever method the backend has when copying on a single file-system. Not all FSs necessarily have a native copy function.
