### ISSUE TITLE
os.PathLike support for Python >=3.6

### ISSUE THREAD

**Issue by Ewande** [dask/s3fs#166]
Since regular Python filesystem interface supports `pathlib.Path`, it would make sense to create S3-version of this class by extending `os.PathLike` (called e.g. `S3Path`). Would it be something you consider useful? I can work on a PR.

**Comment by martindurant** [comment]
Are you interested in implementing this in the context of [fsspec](https://github.com/martindurant/filesystem_spec/) so this it could, eventually, be useful across all file-systems? I have personally never been convinced by `Path`s, but I gather some people find them useful.

**Comment by Ewande** [comment]
Do you mean providing `Path`-based interface for all file systems available in `fsspec`? Wouldn't it mean providing essentially a complete alternative to filesystem-based approach?

**Comment by martindurant** [comment]
Well I don't know - whatever you were proposing here, it should be the same for all file-systems, I would think.

**Comment by Ewande** [comment]
Ok, I see two things here:
- support for using `pathlib.PurePath` in `s3fs` (and `fsspec`)
- creating classes that implement `os.PathLike` interface for each file system in `fsspec`

The first one is quite easy, it's only about supporting `pathlib.PurePath` in places where only pure string is currently supported, e.g. `ls`, `glob`. 
The second one is more complex and is about implementing an alternative for filesystem-based approach, e.g. `S3FileSystem().exists(path)` becomes `S3Path(path).exists()`.

Currently, I'm interested in the first one. Question to you: are you planning to include `s3fs` in `fsspec`?

**Comment by martindurant** [comment]
I suppose we were talking about the first one - but would it simply mean getting the string representation of a Path at every endpoint of the API? I wouldn't imagine taking a Path in `ls()` and returning more Path objects.

**Comment by martindurant** [comment]
Closing as old and not convincing; feel free to propose `__fspath__` in fsspec.

**Comment by quantology** [comment]
For posterity's sake: this has been implemented by @sretlawd in a [gist](https://gist.github.com/sretlawd/bf977ee1d049bbfaed0e9d823fad89f5) (see discussion in fsspec [here](https://github.com/intake/filesystem_spec/issues/114)).
