### ISSUE TITLE
When creating a new S3FileSystem the connection is not refreshed

### ISSUE THREAD

**Issue by om-henners** [dask/s3fs#167]
### Requirements:

- A default IAM role with credentials in `~/.aws/credentials`
- A second IAM role in the same `~/.aws/credentials` file, with access to different S3 buckets

### Steps to reproduce:

1. Create an `S3FileSystem` object without anonymous access as follows:
   ```python
   fs = s3fs.S3FileSystem()
   ```
2. List all visible buckets:
   ```python
   fs.ls('')
   ```
3. Create a new `boto3` Session using a different IAM role, and create a new `S3FileSystem` using this session:
    ```python
   import boto3
   session = boto3.session.Session(profile_name='secondary_role')
   secondary_fs = s3fs.S3FileSystem()
   ```
4. List the buckets for `secondary_fs`:
    ```python
   secondary_fs.ls('')
   ```
Even though the two lists of buckets should be independent, the second will just be a repeat of the first.

### Discussion:

From what I can see this is because when the `connect` method is called in `S3FileSystem.__init__` the `refresh` is defaulted to `False`, and the token that matches existing connections doesn't include the session.

I think the simplest solution might be to include self.session in the `tokenize` call - as far as I can see it's only called in `__init__` and `__setstate__`. Happy to drop a pull request if you agree.

Thanks for all the hard work all!

**Comment by martindurant** [comment]
Each instance creates its own `Session` and so your second call to `S3FileSystem` is not aware that you have created a new `Session` in some other variable. What you actually wanted to do, I think, was:
```
secondary_fs = s3fs.S3FileSystem(profile_name='secondary_role')
```

Alternatively, if you want to explicitly give a hand-tuned `Session` instance or share between file-system instances, you can do that too:
```
secondary_fs = s3fs.S3FileSystem(session=session)
```

**Comment by om-henners** [comment]
Thanks! The first solution worked for me!

I would note though that the second solution won't work as expected regardless - if you pass two hand-rolled sessions to the constructor you still end up with the issue I encountered earlier - with the client being recycled because the session that's passed in isn't used to determine the hash of the stored client object (as the hashed clients are stored on the Client class, not individual instances - not sure if that's desired behaviour or not).

Thanks again!

**Comment by martindurant** [comment]
> as the hashed clients are stored on the Client class

Yes, I suppose you are right about the hashing, it would have been reasonable to pass the `refresh` kwargs in the constructor to avoid reusing instances, if desired; or to include the `id` of the session passed in in the hash.

**Comment by chanhosuh** [comment]
I don't understand why the old client, the one created from the cached connection, is used when the new passed-in session is being used, i.e. cache is overridden?

Here's the relevant code snippet:
```python
def connect(self, refresh=False):
        [...]
        if refresh:
            self._conn.pop(tok, None)
        if tok not in self._conn:
            [...]
        else:
            s3, session = self._conn[tok]
            if not self.passed_in_session:
                self.session = session

        return s3
```

I would expect in the "else" branch, something like:
```python
if self.passed_in_session:
    s3 = s3.session.s3
else:
    s3, session = self._conn[tok]
    self.session = session
```

Actually, I prefer @martindurant 's suggestion to use `id(self.session)` as part of the hash (`tok`).  As also suggested, it would also be good to include `refresh` as an `__init__` kwarg because that makes the logic clearer at first glance (documented in the docstring etc).  

Is there any plan to include any of the above options in future work?

**Comment by yi-ye-zhi-qiu** [comment]
Not sure if it's good practice to ignore `profile_name` in favor of providing environment variable access keys, but if you're in this position, an easy way to refresh could be: 

```python
import aiobotocore 
import s3fs 
import os

fs = s3fs.S3FileSystem()
fs.ls('')

# Refresh instance
session = aiobotocore.session.AioSession()
fs = s3fs.S3FileSystem(session=session, key=os.getenv('SECONDARY_AWS_KEY'), secret=os.getenv('SECONDARY_AWS_SECRET'))
fs.ls('')
```
