### ISSUE TITLE
Response code for put() success/ failure

### ISSUE THREAD

**Issue by ShubhamRathi** [dask/s3fs#169]
I am putting a local file to my S3 Bucket using the .put() call. I want some kind of a return code or something that I get a confirmation if my file has been uploaded to the bucket or not. Is there any mechanism for this?

**Comment by martindurant** [comment]
Have you ever had a case where the upload failed but you got no exception?

**Comment by martindurant** [comment]
In short, I would say that a failure does indeed cause an exception, and a lack of exception can be deemed a success.
