### ISSUE TITLE
Bug involving `ls` on a bucket with many Keys

### ISSUE THREAD

**Issue by TomAugspurger** [dask/s3fs#17]
I'm unable to read a CSV file that I know exists. It looks like it has to do with `ls` not finding the file, because there are many files above it, and `list_objects` returns a limit of 1000 objects.

```python
In [1]: import s3fs

In [2]: fs = s3fs.S3FileSystem(anon=False)

In [3]: df = pd.DataFrame(np.arange(20).reshape(-1, 2))

In [4]: with fs.open('vehcuity/a/b.csv', 'wb') as f:
   ...:     f.write(df.to_string().encode('utf8'))
   ...:

In [5]: import boto3

In [7]: client = boto3.client('s3')

In [8]: obj = client.get_object(Bucket='vehcuity', Key='test.csv')  # it exists
In [10]: with fs.open('vehcuity/a/b.csv', 'rb') as f:
    ...:     print(f.read())
 ... #OSError, file wasn't found
```

Looking at the traceback,

```python
ipdb> len(self._ls(path))
1000
```

It seems that `list_objects` only fetches the first 1000 keys. http://boto3.readthedocs.org/en/latest/reference/services/s3.html#S3.Client.list_objects, they suggest

> You can use the request parameters as selection criteria to return a subset of the objects in a bucket.

As a partial solution, we could filter on the subdirectory with `Prefix='a/'`. That could still fail if the `'a'` "directory" has more that 1,000 keys in it.

**Comment by TomAugspurger** [comment]
Matt, looking into replacing the pandas code with `s3fs`. The first thing that came up was `S3File`s not being iterators/having a readline method? Design-wise, are there any objections to me adding those?

**Comment by mrocklin** [comment]
Sounds great to me.  Might also want to ping @martindurant to see if he has thoughts (he wrote most of s3fs.)

**Comment by martindurant** [comment]
The `ls` issue can be solved without using the prefix - since the directory list is cached, it should not affect performance much except for the special case of writing many small files.

On readline, this presumably involves implementing a text-mode, which we weren't thinking of doing in the near term. You are of course very welcome to implement.

**Comment by martindurant** [comment]
Does adding `MaxKeys=2**16` (or whatever number) to the list_objects fix this for you? There is also the alternative of `.list_objects(Bucket='distributed-test', Delimiter='/').get('CommonPrefixes')`

**Comment by mrocklin** [comment]
Does supporting iteration necessitate supporting text mode?  We implemented `readline` and `__iter__` in `hdfs3`.

**Comment by martindurant** [comment]
True, that should work here too indeed.
