### ISSUE TITLE
Listing more than 1000 files

### ISSUE THREAD

**Issue by SeguinBe** [dask/s3fs#171]
Hello,

I have trouble listing more than 1000 files with s3fs while not having trouble with boto3.

```python
bucket = get_boto3_bucket(BUCKET_NAME)
keys = list(bucket.objects.filter(Prefix=FOLDER_NAME))

import s3fs
fs = s3fs.S3FileSystem(**CONNECTION_ARGS)
files = fs.ls(f"{BUCKET_NAME}/{FOLDER_NAME}")

len(keys), len(files)  # Outputs (1132, 1000)
```

As far as I understand, pagination should be handled properly to avoid the hardlimit of 1000 elements (#21). I use a non-AWS endpoint though, so maybe I should check with our University provider?

**Comment by martindurant** [comment]
Indeed, listing more than 1000 items should be fine, and s3fs uses the boto3 client's `get_paginator` method to achieve this. Anything that you can do to help investigate this would be appreciated.

**Comment by martindurant** [comment]
Closing as stale
