### ISSUE TITLE
Odd cache behaviour

### ISSUE THREAD

**Issue by maartenbreddels** [dask/s3fs#185]
I'm was trying out s3fs with the new h5py with pretty large files (100gb and 1tb). Trying to access the root group keys, it look a long time. I monkey patched some functions with loggers to see what was getting accessed, and it seems with `default_fill_cache=True`, large parts of the file are being read.

Logging the function/methods calls with its arguments, I get:
```
>>>> h5f.keys()
seek (136,) {}
read (544,) {}
_fetch (136, 680) {}
seek (1072,) {}
read (328,) {}
_fetch (1072, 1400) {}
_fetch_range (<botocore.client.S3 object at 0x11399f160>, 'xxx', 'yyy.hdf5', None, 1032, 2424) {'req_kw': {}}
seek (85376007560,) {}
read (328,) {}
_fetch (85376007560, 85376007888) {}
_fetch_range (<botocore.client.S3 object at 0x11399f160>, 'xxx', 'yyy.hdf5', None, 2424, 85376008912) {'req_kw': {}}
```
As you can see the last request seems kind of odd: bytes 2424 to 85376008912 are fetched.

FYI: default_block_size=1024

**Comment by maartenbreddels** [comment]
Amazing work btw!

**Comment by martindurant** [comment]
I guess [here](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L1344), the cache should only be "filled" in the case that the gap between the current location and the requested location is less than a block?

btw, fsspec contains a [memory-map cache](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py#L994) which would be very interesting in this kind of situation, and should work with s3fs (there is an stale branch on here for fsspec compatibility). If you have an interest, it would be very nice to pull it in and see how well it works for your situation.

**Comment by maartenbreddels** [comment]
Yes, I don't really follow the logic of the caching here, but that seems to be the issue indeed.

That is exactly what I want actually. I'm doing this for [vaex](https://github.com/vaexio/vaex/ ) actually, and I want in the end the file to be completely cached on an SSD. I was thinking of doing this at the DataFrame level, but doing it on file/byte level is much easier and portable. Using this I don't have to wait till the file is completely transferred, and most columns aren't used very often anyway. 

Very interesting work.
