### ISSUE TITLE
different behavior of open method between 2.7 and 3.6 

### ISSUE THREAD

**Issue by aharonen** [dask/s3fs#187]
Hi,

I have this code snippet **_a.to_csv(S3FileSystem(anon=False).open(filename,mode='wb'))_** that worked perfectly on python 2.7, what I am doing here is uploading pandas dataframe to s3 bucket as csv file. 
Now i need to convert this code to work with python 3.6 and it fails with this error message "a bytes-like object is required, not 'str'", does someone have any idea what can cause that and what is needed in order to fix that?

Thanks,
Ronen

**Comment by martindurant** [comment]
Are you sure you need to do this, can't just use 
```
 a.to_csv("s3://bucket/filename")
```

but you are right, that `to_csv` produces *text*, which could be written to a bytes-mode file in py2 but not in py3. There are lots of things you could do, like encoding the text yourself, but the simplest would be to open the file as text: `mode='wt'`.

**Comment by aharonen** [comment]
Wow man... that was one of the bests :-)
If no one understood, this solution worked perfect for  me...thanks a lot
