### ISSUE TITLE
`passed_in_session` does not override cached S3 client

### ISSUE THREAD

**Issue by chanhosuh** [dask/s3fs#188]
This issue came up in connection with #167.

I don't understand why the old client, the one created from the cached connection, is used when the new passed-in session is being used, i.e. cache is overridden?

Here's the relevant code snippet:
```python
def connect(self, refresh=False):
        [...]
        if refresh:
            self._conn.pop(tok, None)
        if tok not in self._conn:
            [...]
        else:
            s3, session = self._conn[tok]
            if not self.passed_in_session:
                self.session = session

        return s3
```

I would expect in the "else" branch, something like:
```python
if self.passed_in_session:
    s3 = s3.session.s3
else:
    s3, session = self._conn[tok]
    self.session = session
```

Actually, I prefer @martindurant 's [suggestion][1] in the above issue thread to use `id(self.session)` as part of the hash (`tok`).  As also suggested, it would also be good to include `refresh` as an `__init__` kwarg because that makes the logic clearer at first glance (documented in the docstring etc).  

Is there any plan to include any of the above options in future work?  

[1]: https://github.com/dask/s3fs/issues/167#issuecomment-466808491

**Comment by martindurant** [comment]
In #161 's version, which depends on `fsspec`, the whole s3 instance is cached (keyed on input parameters), and the [`connect`](https://github.com/dask/s3fs/blob/6fef63a5cd19819041823d48e81a1c36aedb0ea5/s3fs/core.py#L204) method makes a new client whenever `refresh=True`; but it does keep the initial `session`, if it was given. This is the future of s3fs, interested in your thoughts.
