### ISSUE TITLE
Dask CI failing due to Python 3.6 requirement

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#191]
```
+++pip install --quiet --upgrade --no-deps git+https://github.com/dask/s3fs
s3fs requires Python '>= 3.6' but the running Python is 3.5.6
```

This is currently causing Dask CI jobs to fail: https://travis-ci.org/dask/dask/jobs/552521747

**Comment by TomAugspurger** [comment]
Working around this for now in https://github.com/dask/dask/pull/5033. Depending on when the next s3fs release is expected, it may make sense to reinstate support for 3.5 I think NumPy and Pandas still support 3.5.

**Comment by mrocklin** [comment]
Note that I don't think that this is released yet, it's just when we
interact with master that things fail

See also https://github.com/dask/s3fs/issues/191

**Comment by martindurant** [comment]
I should have seen this coming...

Indeed, this is not released (I released the pre-change version just before the merge), but it does also bring in the fsspec dependency, which was the whole point.

For the record, I thought the surveys showed that even fewer people were using py35 than py27; but of course I'll fix this.

**Comment by martindurant** [comment]
(makes me take away by f-strings :( )

**Comment by martindurant** [comment]
https://github.com/intake/filesystem_spec/pull/63 
Should add pip-install of fsspec from master wherever s3fs is installed from master (because we use upgrade but no-deps)

**Comment by martindurant** [comment]
https://github.com/dask/s3fs/pull/193 still failing on py35, I don't know why (seems to be calling real AWS and failing credentials). Boto3 is not as updated for py35, but other versions seem to be OK.

**Comment by martindurant** [comment]
pushed in py35 now. This issue should go away with luck.
