### ISSUE TITLE
TypeError: multiple values for keyword argument 'read_timeout'

### ISSUE THREAD

**Issue by keurcien** [dask/s3fs#198]
I wanted to increase the value of `read_timeout` parameter (passed to botocore.config.Config) but it seems like it shouldn't be passed from the config_kwargs:

```python
# from s3fs/core.py in connect(self, refresh)
conf = Config(connect_timeout=self.connect_timeout,
    read_timeout=self.read_timeout,
    **self.config_kwargs)
```
Passing `read_timeout` would raise the following error:
```python
TypeError: type object got multiple values for keyword argument 'read_timeout'
```

Here's my MWE:
```python
import s3fs
s3 = s3fs.S3FileSystem(config_kwargs={'read_timeout': 500})
```

As a hacky workaround, I can set another parameter to some value, e.g:
```python
s3 = s3fs.S3FileSystem(config_kwargs={'max_pool_connections': 50})
```

And then I can set the value of `read_timeout` without raising any error:
```python
s3 = s3fs.S3FileSystem(config_kwargs={'read_timeout': 500})
print(s3.config_kwargs)
```

**Comment by martindurant** [comment]
For some reason I can't remember, `read_timeout` is implemented as a class attribute, so you would have to do
```
s3fs.S3FileSystem.read_timeout = 500
s3 = s3fs.S3FileSystem(..)
```

**Comment by keurcien** [comment]
Oh ok, I see, thanks for the very quick reply!

**Comment by martindurant** [comment]
Works, OK to close?
