### ISSUE TITLE
Unnecessary _parent() call

### ISSUE THREAD

**Issue by nmodhipallise** [dask/s3fs#200]
https://github.com/dask/s3fs/blob/b7638b52f98d819960426c05fc9b72862165105b/s3fs/core.py#L487

I think the `_parent(path)` call is not necessary here. `super().info()` already does this:
https://github.com/intake/filesystem_spec/blob/8175fbdf963fa459f3f69253356b0d3e82dd9d37/fsspec/spec.py#L470

Because of the dual `_parent()` call,
`S3FileSystem.info("bucket/somefile.ext")`
will cause:
`S3FileSystem._ls("")`
which causes:
`S3FileSystem._lsbuckets()`
while it should actually be doing:
`S3FileSystem._lsdir("bucket")`

**Comment by martindurant** [comment]
Hmmm. You are right, that listing two directories up is not useful.
However, if you simply remove it, then 
```
S3FileSystem.ls("bucket/somefile.ext") != [S3FileSystem.info("bucket/somefile.ext")]
```
as it should
