### ISSUE TITLE
fs.open() requires ListBuckets unnecessarily on 0.3.0

### ISSUE THREAD

**Issue by abarrafo** [dask/s3fs#206]
We are unable to ListBuckets and can only work with bucket/objects directly. I am not sure why an fs.Open() requires the ListBuckets Action anyways, we are providing directly the name of the bucket and the key which is enough to work with boto3. 

In fact, s3fs `pip install s3fs==0.2.2` does not have this problem. 

Example: Create a IAM policy that blocks ListBuckets Actions for a user, then attempt: 
```
import pandas as pd
import s3fs
df = pd.read_csv('s3://mybucket/mycsv.csv', nrows = 100)
``` 

Again v0.2.2 works fine, on 0.3.0, we get: AccessDenied ListBuckets error.

**Comment by martindurant** [comment]
This should be fixed on master ( #203 , #204 ). A release should come soon.

**Comment by martindurant** [comment]
Please feel free to test for yourself, if you have a moment.

**Comment by abarrafo** [comment]
Can confirm the problem is resolved on `master`.
