### ISSUE TITLE
refresh arg for glob is gone in 0.3

### ISSUE THREAD

**Issue by flixr** [dask/s3fs#207]
s3fs 0.2.1 has the `refresh` arg for `glob` as introduced with #172 

With the merge of #161 this is now gone in 0.3x again...

**Comment by martindurant** [comment]
Hm, yes, you are quite right. You can, of course, use `.invalidate_cache()` directly, if you wish.
This will be tricky to re-introduce, as the argument needs to get to `ls`, but `glob` (defined in fsspec) calls `walk` first - each could have kwargs, that get passed down the chain.

**Comment by flixr** [comment]
Would calling `invalidate_cache()` be equivalent to the old `refresh=True` or was the refresh actually smarter and invalidate only the part that was being globbed?

**Comment by martindurant** [comment]
You can call it with no argument, which clears everything, or with specific directories to clear. The refresh argument cleared directories as it encountered them, so a little smart.

**Comment by flixr** [comment]
That's what I thought.... was quite handy...

**Comment by martindurant** [comment]
As well as re-adding this, it would also be handy to implement a version of invalidate_cache which cleared a directory and everything under it

**Comment by martindurant** [comment]
fsspec now supports passing kwargs around, so if you install from master, it will work. It also requires the following change in s3fs, to be added after the next release of fsspec:
```diff
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -849,10 +849,10 @@ class S3FileSystem(AbstractFileSystem):
             self.dircache.pop(path, None)
             self.dircache.pop(self._parent(path), None)

-    def walk(self, path, maxdepth=None):
+    def walk(self, path, maxdepth=None, **kwargs):
         if path in ['', '*', 's3://']:
             raise ValueError('Cannot crawl all of S3')
-        return super().walk(path, maxdepth=maxdepth)
+        return super().walk(path, maxdepth=maxdepth, **kwargs)
```

**Comment by flixr** [comment]
:+1:
