### ISSUE TITLE
How to set the ContentType='image/jpeg' during upload

### ISSUE THREAD

**Issue by ShubhamRathi** [dask/s3fs#211]
I'm uploading a set of images via s3fs. 
Until 10 days ago, this script did the content type setting for me: 
`fs.put(updatedPath, s3filepath, ContentType='image/jpeg')`
Recently, this is not working. Has something changed?

How do I set the content type during upload?

**Comment by martindurant** [comment]
Could you perhaps try with [this branch](https://github.com/intake/filesystem_spec/pull/87) of `fsspec`, please?

**Comment by martindurant** [comment]
That PR has merged, this will work again on master

**Comment by ShubhamRathi** [comment]
This is still a persisting issue.

**Comment by TomAugspurger** [comment]
@ShubhamRathi do you have an example of it failing with the latest versions of fsspec and s3fs?
