### ISSUE TITLE
Whole file buffering

### ISSUE THREAD

**Issue by martindurant** [dask/s3fs#23]
The caching scheme is made for some process interacting with only some limited part os a massive file. If a huge file is opened and read beginning to end, eventually the whole thing will be cached in memory, which may not be possible. Should there be a "streaming mode" where, although we can still read ahead, when we get passes data it gets cleaned?

**Comment by mrocklin** [comment]
Clearing out extraneous parts of the buffer sounds good to me.

**Comment by martindurant** [comment]
Drop data more than blocksize earlier in the file than the current location?

**Comment by mrocklin** [comment]
Sure?  Honestly I'm probably not as informed on current system or the best way to do this as you are.
