### ISSUE TITLE
FileNotFoundError when calling info

### ISSUE THREAD

**Issue by sbchisholm** [dask/s3fs#238]
When calling `info` on a file that has been uploaded to S3 after `info` has already been called on another file in the same prefix, s3fs reports a FileNotFoundError, here's a code snippet that reproduces the behaviour.  

```python
import s3fs
import boto3


bucket_name = "bucket"
prefix = "data"

s3 = s3fs.S3FileSystem()
bucket = boto3.resource('s3').Bucket(bucket_name)

def test(filename):
    key = f"{prefix}/{filename}"
    with open(filename, 'rb') as data:
        bucket.upload_fileobj(data, key)
    info = s3.info(f"{bucket_name}/{key}")
    print(f"{key} info: {info}")


def main():
    test("file1")
    test("file2")


if __name__ == "__main__":
    main()
```

output:
```
python s3fs_info_test.py
data4/file1 info: {'Key': 'bucket/data/file1', 'LastModified': datetime.datetime(2019, 9, 13, 17, 30, 16, tzinfo=tzutc()), 'ETag': '"664888fac652413c3a57c2e669d5d2b5"', 'Size': 151645, 'StorageClass': 'STANDARD', 'type': 'file', 'size': 151645, 'name': 'bucket/data/file1'}
Traceback (most recent call last):
  File "s3fs_info_test.py", line 25, in <module>
    main()
  File "s3fs_info_test.py", line 21, in main
    test("file2")
  File "s3fs_info_test.py", line 15, in test
    info = s3.info(f"{bucket_name}/{key}")
  File "/home/steve/.virtualenvs/partition_stats-RqvIULMs/lib/python3.7/site-packages/s3fs/core.py", line 498, in info
    return super().info(path)
  File "/home/steve/.virtualenvs/partition_stats-RqvIULMs/lib/python3.7/site-packages/fsspec/spec.py", line 509, in info
    raise FileNotFoundError(path)
FileNotFoundError: bucket/data/file2
```

Not sure if it's the best way to fix it (or if it even does fix the issue) but in `def info` you could try wrapping `return super().info(path)` in a `try/except` and if it's a `FileNotFoundError`, call `info` again but pass `refresh=True`.

The use case for us is that we have a lambda subscribed to bucket notifications for objects that are created, and what is happening is that when the lambda container is reused consecutive files that are uploaded to the same prefix fail with a `FileNotFoundError`.  After some time goes by (long enough to get a fresh lambda container) retrying the same bucket notification event works fine.

For now we've pinned at 0.2.1, which doesn't have this bug.

**Comment by martindurant** [comment]
Instead of 
```
with open(filename, 'rb') as data:
        bucket.upload_fileobj(data, key)
```
You should do
```
s3.put(filename, f"{bucket_name}/{key}")
```

The s3 instance cannot know that the underlying file listing has changed. If you really must change the files in other methods (or from another process/node), you can always call `s3.invalidate_cache(..)` or `s3.ls(.., refresh=True)`.

**Comment by sbchisholm** [comment]
Thanks for the quick response.  The `upload_fileobj` calls in the example are just to illustrate a  point, in that for our use case, the files are being uploaded by other processes/applications outside of our control.  So yes it makes sense that the cache would be updated if we using the same s3fs instance to upload the files.

I suppose what I was suggesting is that rather than immediately raise FileNotFoundError if the directory is in the cache but the file isn't present, except that exception and try again with the refresh option set to `True`, then you'll be providing more of a best effort.  I understand that calling `invalidate_cache` before opening the file would work too but the `try/except` suggestion would arguably keep a better level of abstraction.

**Comment by martindurant** [comment]
It is a valid argument. Please make a PR with this change, and encourage other team members to discuss.

**Comment by rambej0201** [comment]
def lambda_handler(event,context):
    BUCKET_NAME = event['Records'][0]['s3']['bucket']['name']
    s3 = s3fs.S3FileSystem(anon=False)
    _filename = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
    print("File to be read:" + BUCKET_NAME + "/" + _filename)
    reader = DataFileReader(s3.open(f"{BUCKET_NAME}/{_filename}", "rb"), DatumReader())

I am still facing below error

[ERROR] FileNotFoundError: myBucketName/myEventName.avro
Traceback (most recent call last):
  File "/var/task/aggr.py", line 18, in data_driver
    reader = DataFileReader(s3.open(f"{BUCKET_NAME}/{_filename}", "rb"), DatumReader())
  File "/var/task/s3fs/core.py", line 352, in open
    s3_additional_kwargs=kw)
  File "/var/task/s3fs/core.py", line 1210, in __init__
    info = self.info()
  File "/var/task/s3fs/core.py", line 1228, in info
    refresh=refresh, **kwargs)
  File "/var/task/s3fs/core.py", line 537, in info
    raise_from(FileNotFoundError(path), e)
  File "<string>", line 3, in raise_from

**Comment by sbchisholm** [comment]
@rambej0201 after some reflection I'm thinking we shouldn't bother with a PR to accommodate the lambda use case.  It seems perfectly reasonable to have to call `invalidate_cache` at the beginning of your lambda_handler.  What is a bit unexpected for me was that the cache seems to be maintained between instances of `S3FileSystem()`.

So just make sure you invalidate the s3fs cache at the beginning of your lamba handler and you should be all good.

**Comment by rambej0201** [comment]
@sbchisholm I am quite new to these resources. I am more Java guy. can you please help me to understand your suggestions about invalidating the s3fs cache at the beginning of my lamba handler 

I tested like below still I am facing FileNotFoundError

s3 = s3fs.S3FileSystem(anon=False)

def lambda_handler(event,context):
BUCKET_NAME = event['Records'][0]['s3']['bucket']['name']
_filename = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
print("File to be read:" + BUCKET_NAME + "/" + _filename)
reader = DataFileReader(s3.open(f"{BUCKET_NAME}/{_filename}", "rb"), DatumReader())

**Comment by sbchisholm** [comment]
@rambej0201 You can just make the first line of your `lambda_handler` call: `s3.invalidate_cache()`.  The reason you're seeing the FileNotFound error is because s3fs and its cache is being initialized outside of your handler.  Everything outside the handler can live on for several invocations of your lambda function.  

It looks like your lambda is subscribed to bucket notification events which means (i think i can assume) that your s3 bucket is changing between invocations.  These changes make the state of the s3 bucket out of sync with the cache in s3fs.  So if you reset the cache a the beginning of each invocation you should be able to resolve your issue.

**Comment by rambej0201** [comment]
@sbchisholm my below code declaration is still giving me FileNotFoundError 

import json
import avro
import pandas as pd
from avro.datafile import DataFileReader
from avro.io import DatumReader
from pandas.io.json import json_normalize
import s3fs
import urllib.parse
import os
import time
import boto3
from datetime import datetime, timezone

def lambda_handler(event,context):
    BUCKET_NAME = event['Records'][0]['s3']['bucket']['name']
    _filename = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
    s3 = s3fs.S3FileSystem(anon=False)
    x = BUCKET_NAME + "/" + _filename
    s3.invalidate_cache(x)
    print("File to be read:" + x)
    reader = DataFileReader(s3.open(f"{BUCKET_NAME}/{_filename}", "rb"), DatumReader())
    for record in reader:
        print(record)

**Comment by sbchisholm** [comment]
@rambej0201 have you tried not passing an argument to `invalidate_cache` perhaps you're not passing in the correct value for `x` to clear just the one cache entry (passing in no arguments should clear everything in the cache).

**Comment by rambej0201** [comment]
@sbchisholm I actualy tried that first during last night. After going through the default parameter suggestion on pycharm I have passed the path as parameter.

def lambda_handler(event,context):
    BUCKET_NAME = event['Records'][0]['s3']['bucket']['name']
    _filename = urllib.parse.unquote_plus(event['Records'][0]['s3']['object']['key'], encoding='utf-8')
    s3 = s3fs.S3FileSystem(anon=False)
    x = BUCKET_NAME + "/" + _filename
    s3.invalidate_cache()
    print("File to be read:" + x)
    reader = DataFileReader(s3.open(f"{BUCKET_NAME}/{_filename}", "rb"), DatumReader())
    for record in reader:
        print(record)

I have tried today with above I am still facing the same FileNotFoundError. I have also deleted previously used resources S3 bucket & lambda function and deleted new resources. I am testing in Sandbox

**Comment by martindurant** [comment]
#279 might be related, if your bucket has many files.

**Comment by rambej0201** [comment]
@martindurant currently I am testing with only limited objects not more than 10 on my S3 bucket. Still I am unable to access the avro file to parse to DataFileReader to read the avro file

**Comment by rambej0201** [comment]
@sbchisholm @martindurant thank you so much for helping me. It was actually worked fine from 03Feb2020. I am sorry I am late to update I was busy

**Comment by martindurant** [comment]
Hurray! Thanks for letting us know.
I will close this, but the general theme of file listings caching remains in scope.

**Comment by rambej0201** [comment]
@martindurant I actually got FIleNotFoundError for some events during 05Feb2020 than I made sure about s3.invalidate_cache() on the API
