### ISSUE TITLE
s3.open() doesn't seem to understand user defined encoding

### ISSUE THREAD

**Issue by wtfzambo** [dask/s3fs#241]
I have an utf-8 encoded .csv file with user defined data that I'm trying to upload to my s3 bucket.

My script is like this. It works perfectly with a dummy dataframe, and it also works if I try to save my data locally with in-built `open()` function, but with my .csv it breaks at the last line:
```python
# [..] other stuff
s3 = s3fs.S3FileSystem(session=session)
with s3.open('my_bucket/my_file.csv', 'w', encoding='utf-8') as output:
        data.to_csv(output, index=False, encoding='utf-8')
```
and here's the traceback:
```
Traceback (most recent call last):
  File "s3_csv_gz.py", line 35, in <module>
    upload(file_path)
  File "s3_csv_gz.py", line 30, in upload
    data.to_csv(output, index=False, encoding='utf-8')
  File "C:\Anaconda\lib\site-packages\pandas\core\generic.py", line 3020, in to_csv
    formatter.save()
  File "C:\Anaconda\lib\site-packages\pandas\io\formats\csvs.py", line 172, in save
    self._save()
  File "C:\Anaconda\lib\site-packages\pandas\io\formats\csvs.py", line 288, in _save
    self._save_chunk(start_i, end_i)
  File "C:\Anaconda\lib\site-packages\pandas\io\formats\csvs.py", line 315, in _save_chunk
    self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 72, in pandas._libs.writers.write_csv_rows
  File "C:\Anaconda\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14-22: character maps to <undefined>
```

As you can see from the last call, for some reason the module called is `cp1252.py`, instead of `utf-8.py`. Now, I'm not 100% sure if that's how it's supposed to work, but I'm quite certain that cp1252 has nothing to do with utf-8.

Is there a way to circumvent this? I'd really love to use this package instead of boto3 to upload my files, but I can't seem to make it work.

**Comment by martindurant** [comment]
The encoding step is simply to call `io.TextIOWrapper` on the bytes-mode file and pass through parameters. You could try this to see if it behaves differently, in which case we have something to fix. Might cp1252 be your locale encoding (`locale..getpreferredencoding(False)`) ?

**Comment by wtfzambo** [comment]
So, cp1252 was indeed the preferred encoding. Forcing windows 10 to use UTF-8 as locale indeed made my script work.

It's weird tho, my default locale shouldn't be affecting what's going on if I specifically set it in my python program.

**Comment by martindurant** [comment]
So it seems like your encoding= kwargs is not being passed on to TextIOWrapper in fsspec.AbstractFileSystem.open - could you debug why this is?

**Comment by wtfzambo** [comment]
Hold on, I'm not very proficient with this yet. I'll need a bit more guidance.

Right now, the encoding is set like this:
```python
s3 = s3fs.S3FileSystem()
s3.open(encoding='utf-8')
```

Is there something different I should be doing?

**Comment by martindurant** [comment]
I mean
```
with s3.open(path, 'wb') as f:   # binary mode
    fo = io.TextIOWrapper(f, mode='w', encoding='utf-8')
    data.to_csv(fo, ...)
```

**Comment by wtfzambo** [comment]
@martindurant 
Hi, sorry for the late reply, I was away for the weekend and didn't take my laptop with me.
Anyway, I switched back to system default encoding being cp1252, then tried your snippet and it works!

I'm a bit confused now and forgive me for the ignorance:
In the original snippet I opened the path to s3 file with `s3.open(mode='w')`, whereas in this case we open it with `s3.open(mode='wb')`... what's the catch? 

PS: (also, I skipped `mode='wb'` in the io.TextIOwrapper call because there's no such argument).

**Comment by martindurant** [comment]
Ah, so there was indeed a bug, fixed in the linked PR.
In way you are doing it now with 'wb', the file is open in binary mode, and I suppose pandas is doing the right thing in dealing with that.

**Comment by wtfzambo** [comment]
For testing purposes I tried to recreate locally what you suggested in the snippet above, like this:
```python
with open('local_file.csv', 'wb') as f:   
    fo = io.TextIOWrapper(f, encoding='utf-8')
    data.to_csv(fo, ...)
```
The script produced no errors, but for some reason the output file turned out empty, contrary to what happened using s3.open. Any idea why this might happen?

PS:
Now that you fixed the bug, to get the latest version do I just run "conda update fsspec" ?

**Comment by wtfzambo** [comment]
> Perhaps the object fo needs to be flushed and/or closed before exiting the block.

Hell yeah you're a genius. I confirm that doing fo.flush() before exiting the block indeed works. Man, low-level programming is so convoluted.

On a totally unrelated note, do you have any idea if it's possible to use file compression with this system?
If I try to specify compression, pandas returns me this warning:
```
RuntimeWarning: compression has no effect when passing file-like object as input.
```

> No, it is only on master.

Ah ok. I'll wait for the release, in the meanwhile I can just use the snipped you provided at the beginning as some kind of monkey patch, or the last one you linked.

The app is still in super-early development so I'm not in a rush.
Thanks a lot for all the help!

**Comment by martindurant** [comment]
I am surprised that pandas does not handle that!
With the fsspec route, you can specify compression:
```
myfile = fsspec.open(path, 'wt', encoding='utf-8', compression='gzip')
```
*or* you could use a similar trick to TextIOWrapper with your favourite compression package, e.g., gzip.GZipFile is what gets used internally for the line above. Note that, if doing it by hand, you probably have to flush both the text file and then the compression file buffer too.

**Comment by wtfzambo** [comment]
I was surprised as well, apparently the compression only works when passing a file path as argument and not a file object, for some magical reason. A quick google search shows that it's been already noticed by the community but never addressed.
