### ISSUE TITLE
refresh=True kwarg for info()

### ISSUE THREAD

**Issue by AbdealiJK** [dask/s3fs#247]
I'm a bit confused by some behavior after I upgraded s3fs to v0.3.x

In v0.3.0 - the refresh kwarg has been removed from the info() function:
https://github.com/dask/s3fs/blob/0.3.0/s3fs/core.py#L441

This was there earlier in v0.2.2:
https://github.com/dask/s3fs/blob/0.2.2/s3fs/core.py#L495

In the "latest" and "stable" documentation, it says that `release` is supposed to be there:
https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem.info

I can't find any release notes about what the changes between v0.2 and v0.3 are.
So, I'm super confused on what happened and what I'm supposed to expect ...
 - Is this a bug in the code ?
 - Is this a bug in the documentation ?

it would be nice to have release notes / changelogs to get a hint of what changed rather than digging through git histories

**Comment by TomAugspurger** [comment]
It looks like doc build is failing.

@mrocklin you (and @koverholt, hi Kris) are the only maintainers of s3fs on readthedocs. Could you add Martin (and myself / James) as maintainers?

We need to switch the GitHub / RTD integration from their "service" to a webhook.

**Comment by mrocklin** [comment]
Done.

**Comment by AbdealiJK** [comment]
Ah, I see 
I should have noticed the docs-error badge in the Readme

**Comment by jrbourbeau** [comment]
The documentation build was fixed over in #251 so the docs at https://s3fs.readthedocs.io/en/latest/ should now reflect the current state of things (`refresh` keyword being removed). Thanks for reporting @AbdealiJK!
