### ISSUE TITLE
Integrate with numpy.fromfile

### ISSUE THREAD

**Issue by karlschriek** [dask/s3fs#256]
Really useful library thanks!

I am currently trying to build a workflow where I have a very large dataset (consisting of images on disk) which I convert to batches of Numpy arrays before then writing them batch-wise to a single S3 object. Writing works well enough using boto3's mutlipart upload. However, afterwards I would like to also read this file in batches. Currently I have to first download it to disk, and then use something along the following lines to load in batches:

```
number_of_images=1024 # let's assume we know this
batch_size_to_read=128

number_of_batches = number_of_images / 128

image_width=300
image_height=300
channels=3
bytes_per_image=1314732 #the number of bytes used to store the array for a single image
pixels_per_image=image_width*image_height*channels

for i in range(number_of_batches)
    array_part = np.fromfile(
        file ="/path/local/file.npy",        
        offset=1314732*0,#bytes
        count=pixels_per_image*batch_size_to_read,
        dtype="float32"
    )
    array_part = array_part .reshape(batch_size_to_read, image_width, image_height, channels)

    # ... do further stuff
```

It would very useful instead of first copying the file to disk, to be able to just replace the `file` with and opened `s3fs` file.

I did try using something like:

```
from s3fs.core import S3FileSystem
s3 = S3FileSystem(anon=False)

key = 'my/obejct/key.npy'
bucket = 'my-bucket'

with s3.open('{}/{}'.format(bucket, key)) as f:
        array_part = np.fromfile(file =f, ... )
```

but this results in `io.UnsupportedOperation: fileno`

EDIT:

Nevermind, I discovered that this already intergate seemlessly with numpy.frombuffer, as follows:

```

image_width=300
image_height=300
channels=3
bytes_per_image=1314732 #the number of bytes used to store the array for a single image
start_reading_from=5 # we'll skip the first five images
batch_size_to_read=10 #we'll read 10 images

with s3.open('{}/{}'.format(bucket, key)) as f:
    f.seek(start_reading_from*bytes_per_image)
    bytes = f.read(bytes_per_image*batch_size_to_read)
    ar=np.frombuffer(bytes, dtype="float32").copy()
    ar=ar.reshape((-1, image_width, image_height, channels))

    # ...do stuff

```

**Comment by martindurant** [comment]
Indeed, exactly so. I had to do this too, a pity that numpy doesn't consider the arbitrary file-like object case, perhaps something to do with the option for memmaping.
