### ISSUE TITLE
Getting old file name while accessing folder with ls command

### ISSUE THREAD

**Issue by Edlopushansky** [dask/s3fs#260]
Hello , 
My steps:
1. Create a folder in s3 bucket.
2.Accessing folder to read file that in it.
3. Delete folder.

My issue:
Everything goes fine the first time. 
Second iteration it fails because somehow it reads the old file which already doesn't exist since it was deleted along with entire folder.

Code snippet:
` def _server_connect(self):

        try:
            self._conn = s3fs.S3FileSystem()
            self._s3_client = boto3.client('s3')
            self._s3_resource = boto3.resource('s3')
            return True

        except Exception as e:
            logger.warn(f'Could not establish connection with S3 Server. Check server configuration/name.'
                        f' Exited with error: {e}', html=True)

    def s3_get_verification_code(self, account=None, bucket='prod.ses.robots.aurishealth.uaa' ):
        """
        Retrieves verification code sent to email account

        :param bucket: S3 bucket
        :param account: email account associated with folder in S3 bucket
        :return: verification code
        """

        if self._server_connect():
            time.sleep(5)
            logger.info(f'\nLogged into S3 bucket: {bucket} with account: {account} ', html=True, also_console=True)
            bucket_path = os.path.join(bucket, account, 'inbox')  # accessing bucket inbox folder
            file_path = self._conn.ls(bucket_path) # get a file name in inbox folder
            try:
                for file in file_path:
                    if not file.split('/')[-1].isalnum():
                        logger.info(f'empty folder' ,html=True, also_console=True)
                        continue
                    else:
                        logger.info(f'file {file}', html=True, also_console=True)
                        file_path = file
                        logger.info(f'file_path2 {file}', html=True, also_console=True)
                        break
                try:
                    logger.info(f'going to decode email', html=True, also_console=True)
                    email = self._conn.cat(file_path).decode('utf8')  # reads and decodes context if the file
                    logger.info(f'email {email}', html=True, also_console=True)
                    code = email.split('Your password reset code is')[-1].split('\r')[0].lstrip()
                    logger.info(f'code {code}', html=True, also_console=True)
                    logger.info(f'Retrieved verification code : {code}', html=True, also_console=True)
                    return code
                except Exception as e:
                    raise Exception(f'cannot decode email', e)
            except Exception as e:
                logger.warn(f'Could not find an email body', html=True)`

Is it a some kind of caching is going on in s3 ?

**Comment by martindurant** [comment]
As far as I can tell, you are only calling ls and cat here, and the files are being written elsewhere (perhaps with those boto clients). Yes indeed, s3fs does cache directory listings, because fetching them can be expensive. It also caches file system instances, so you use the most recently created one, if it exists with the same initial parameters (this is being discussed elsewhere). 

Short story: if you want to tell s3fs that you might have changed listings elsewhere, you need to call `self._conn.invalidate_cache()`, passing either the directory that has changed, or passing nothing and discarding all the cache.

**Comment by Edlopushansky** [comment]
Martin, you made my day. It worked like a charm :)) Thank you very much.
