### ISSUE TITLE
.isfile() is returning False

### ISSUE THREAD

**Issue by nojohnny101** [dask/s3fs#268]
We are running pyarrrow from a lambda that uses s3fs to get parquet objects from S3. Pyarrow is throwing an inconsistent error when trying to read objects in, specifically showing that fs.isfile(path) is False. the path is a direct path to an s3 parquet object.

The behavior is strange through, because when a lambda runs from a cold start, it works every time. If you pass in the same key again, it fails and said "non-file path" because fs.isfile() returned false. fs is the filesystem specific in pyarrow as s3fs

this is the relevant code:

s3 = s3fs.S3FileSystem()

ParquetDatset("bucket/2019.parquet", filesystem=s3)

then within Pyarrows library, it does a fs.isfile() on the path that is passed in and it returns false.

Any ideas? This bug has been bothering me for days now and I'm a bit lost of what to look at.

**Comment by martindurant** [comment]
likely duplicate of #253

**Comment by nojohnny101** [comment]
Yes thank you. I'll post on the other.
