### ISSUE TITLE
Q: s3 key object created time ?

### ISSUE THREAD

**Issue by tkang007** [dask/s3fs#270]
Hello,
s3fs looks very helpful and many thanks to all contributors.
I am trying to get key related time with info or ls method, but I cannot find it.

Can you help me how to get a key created time ?

**Comment by martindurant** [comment]
`s3.info('bucket/dir/file')` gives output like:
```
{'Key': 'MDtemp/x.xz',
 'LastModified': datetime.datetime(2016, 8, 20, 13, 1, 18, tzinfo=tzutc()),
 'ETag': '"8dc5aea5b03dff8595f096f9e368e888"',
 'Size': 32,
 'StorageClass': 'STANDARD',
 'type': 'file',
 'size': 32,
 'name': 'MDtemp/x.xz'}
```

I do see a timestamp, is that not good enough?

**Comment by tkang007** [comment]
Thanks  martindurant!.    I was confused with directory type which does not include detail info.
