### ISSUE TITLE
Stop setting logger handlers and levels

### ISSUE THREAD

**Issue by tsibley** [dask/s3fs#282]
This came up re: boto3 and botocore loggers in #262 and was resolved for them, but the `s3fs.core` module still configures a handler and sets the level of the `s3fs` logger:

https://github.com/dask/s3fs/blob/ab6ebbeeaa0cf97d5c71d8556ca6b29082560945/s3fs/core.py#L16-L23

Logging config is something that should generally be owned solely by the application and not interfered with by libraries. The [Python documentation](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) describes this principle as:

> It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library.

Currently, my application's normal logging strategy is interfered with when I use fsspec to handle s3:// URLs via s3fs, and there's no good way to work around it since logging config is loaded very early in the application (as is generally advisable) but s3fs is loaded much later by fsspec on demand.

I think the best solution would be to remove the handler-adding code entirely, but realize that may not abide by backwards compatibility policies for existing behaviour.

As an alternative, adding the handler could be moved into the conditional which sets the level, essentially making it opt-in by setting `S3FS_LOGGING_LEVEL` in the environment.

A final alternative might be to consider calling `logging.basicConfig()` instead, which will do nothing if a root logger is already configured, and otherwise sets up a basic handler like `s3fs.core` is already doing. I think this would be a reasonable compromise, but I'm not entirely certain it wouldn't have other unintended side-effects, such as load-order-dependent quirks.

I'd be happy to provide the patch for any of these options, if it would be merged and released.

**Comment by TomAugspurger** [comment]
Agreed that s3fs shouldn't be configuring the logger.

I'm not sure we have a compatibility policy on logging output. My initial preference is to just make the change, and perhaps provide a helper method to restore the old logging config for folks who aren't familiar with Python's logging.

**Comment by martindurant** [comment]
Feel free to write the PR, if you have the time, with @TomAugspurger 's preference (i.e., rip out the logging setup but allow it to be activated with a function call or at import with an environment variable).

**Comment by tsibley** [comment]
Thanks! PR #283 submitted.
