### ISSUE TITLE
Making new S3FileSystem with different session does not use new session

### ISSUE THREAD

**Issue by mgmarino** [dask/s3fs#284]
Essentially, the session is not considered correctly when caching.  This is an issue especially when the session needs to update periodically (e.g. due to refreshing credentials).  If the old session's credentials expire, s3fs will fail accordingly.  

Here is an example of the problem:

```python
import boto3
import s3fs

session1 = boto3.Session(aws_access_key_id="key1", aws_secret_access_key="secret1", aws_session_token="token1")
session2 = boto3.Session(aws_access_key_id="key2", aws_secret_access_key="secret2", aws_session_token="token2")

s3_one = s3fs.S3FileSystem(session=session1)
s3_two = s3fs.S3FileSystem(session=session2)

print(s3_one.passed_in_session.get_credentials().access_key)
print(s3_two.passed_in_session.get_credentials().access_key)
```

outputs:

```
key1
key1
```

The root problem is that tokenize does not properly take this into account:

```
from fsspec.utils import tokenize
assert tokenize(session=session2) != tokenize(session=session1)
```
fails.

This is of course due to the fact that the string repr of session does not include the token information (likely by design).:

```python
str(session1)
"Session(region_name='eu-west-1')"
``` 

I'm looking at possible workarounds/solutions and will post on the issue when/if I find any.

**Comment by mgmarino** [comment]
A workaround is to explicitly pass in the aws credentials in `client_kwargs` as these tokenized and result in a new client.  

A solution to this issue may be for now simply improved documentation of how these objects are cached (which I would be happy to write).

**Comment by martindurant** [comment]
Interesting corner case...

Separately, on fsspec we are wondering whether/how to disable instance caching and how to select a directory caching strategy (including "none").

**Comment by philbasford** [comment]
There is very similar issue that if pass in boto3 session it is not used and environment bar are used instead. This is due to create_client implementation and not using client of the session.

**Comment by martindurant** [comment]
@philbasford - sorry, I'm a little confused, s3fs does not work with boto3 sessions at all, it depends on aiobotocore.

**Comment by mgmarino** [comment]
This problem was originally with a version of s3fs that, I believe, *did* use `boto3.Session`.  We have also moved on to the newer version and have not seen this problem since.

**Comment by martindurant** [comment]
OK! good to close, then?

**Comment by mgmarino** [comment]
From my side, yes.  Perhaps @philbasford can open a new issue if there is still something going on with the newest version.
