### ISSUE TITLE
MutableMapping

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#29]
It would be convenient to treat an S3 bucket as a `MutableMapping`.  

This might look something like the following `MutableMapping` around a local directory: https://github.com/mrocklin/zict/blob/master/zict/file.py

It would be useful for hosting NDArrays on S3 using an upcoming Zarr refactor: https://github.com/alimanfoo/zarr/pull/22

@martindurant does this interest you?

**Comment by martindurant** [comment]
Certainly very doable, and I'm willing to take this on. 
Performance will depend on the size of the chunks versus number of accesses; such considerations can wait.

**Comment by mrocklin** [comment]
Ideally the mutablemapping interface here would be fairly straightforward and not think about chunks.  On the `zarr` side we leave chunk size up to the user.
