### ISSUE TITLE
Version ID not updated for non-multipart upload

### ISSUE THREAD

**Issue by HieronymusLex** [dask/s3fs#294]
When committing a versioned object, the new Version ID is only updated in the case of a multipart upload however it should ideally also be updated when PutObject is used. See https://github.com/dask/s3fs/blob/master/s3fs/core.py#L1146

I believe on https://github.com/dask/s3fs/blob/master/s3fs/core.py#L1158 the write result should be captured and version ID updated given it is in the PutObject response dict

**Comment by martindurant** [comment]
Fair enough, however, is it not enough to invalidate the cache at the end of the method?

**Comment by HieronymusLex** [comment]
yeah that does the job in most cases. in the scenario where a given process needs to know the version ID of the specific version it just wrote, there might be a race condition (albeit unlikely) if another process writes the same object key before the call to invalidate the cache

**Comment by matteofigus** [comment]
I am pretty sure this doesn't apply anymore as that code has been updated since (see #403). Should we close this one @martindurant ?
