### ISSUE TITLE
unexpected keyword argument 'skip_instance_cache'

### ISSUE THREAD

**Issue by jsheedy** [dask/s3fs#298]
`Version: s3fs==0.4.0`

Passing `skip_instance_cache` to `s3fs.S3FileSystem` as indicated in the [docs](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem) does not succeed:

```
>>> import s3fs
>>> s3fs.S3FileSystem(skip_instance_cache=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josephsheedy/venv/py3/lib/python3.8/site-packages/fsspec-0.6.2-py3.8.egg/fsspec/spec.py", line 52, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/Users/josephsheedy/git/s3fs/s3fs/core.py", line 156, in __init__
    self.s3 = self.connect()
  File "/Users/josephsheedy/git/s3fs/s3fs/core.py", line 228, in connect
    self.session = botocore.session.Session(**self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'skip_instance_cache'
```

Other kwargs `['use_listings_cache', 'listings_expiry_time', 'max_paths']` destined for fsspec are handled in `__init__`, but not `skip_instance_cache`.

**Comment by martindurant** [comment]
Thanks for posting.
Note that this is still unreleased.

**Comment by mdwint** [comment]
This issue is still present in s3fs 0.5.1. `skip_instance_cache` is not passed to the superclass: https://github.com/dask/s3fs/blob/c8ce8a515f7d4e61650bc23742bcdbc25f78cdd1/s3fs/core.py#L198

**Comment by martindurant** [comment]
0.5.2 (available on pypi and shortly on conda-forge) does not appear to have this problem:

```
In [1]: import s3fs

In [2]: s3 = s3fs.S3FileSystem()

In [3]: s3fs.S3FileSystem(skip_instance_cache=True) is not s3
True
```

**Comment by mdwint** [comment]
My bad! I had monkeypatched `s3fs.core.S3FileSystem.__init__` with some default arguments, but didn't realize there was a metaclass `fsspec.spec._Cached` that is supposed to consume the `skip_instance_cache` kwarg. Monkeypatching `fsspec.spec._Cached.__call__` solved the issue.

Context: I'm doing this to pass default arguments to S3FileSystem **when using Dask**. Is there a recommended way of doing this, other than [passing them as `storage_options`](https://docs.dask.org/en/latest/remote-data-services.html#amazon-s3) to the Dask operation? I'd rather not pass them at every call site, but instead configure them once per process globally.

**Comment by martindurant** [comment]
You could use the [configuration](https://filesystem-spec.readthedocs.io/en/latest/features.html#configuration) for this

**Comment by mdwint** [comment]
Thanks @martindurant, that's exactly what I needed! I was confused for a minute because I've been searching for this in the past, but then I noticed that the `fsspec.config` module is new. Great that this was added!
