### ISSUE TITLE
New release (0.4.1) is not supported for Python<3.6

### ISSUE THREAD

**Issue by fgbocci** [dask/s3fs#301]
https://github.com/dask/s3fs/blob/master/s3fs/core.py#L65

uses an f-string and brakes backwards compatibility with python3.5

**Comment by martindurant** [comment]
Thanks for pointing this out. I don't think that 3.5 should be supported any more (along with the rest of the pydata ecosystem), but indeed the package classifiers ought to have been updated before release. Note that the dependency `fsspec` already excludes 3.5.

**Comment by fgbocci** [comment]
No problem! Think that maybe a Deprecation Warning could be added, specially being `0.4.0` to `0.4.1` upgrade a minor fix.
It will only be supported for Python>=3.6 and the package classifier be updated? Just to update our jobs. Thanks!

**Comment by martindurant** [comment]
I believe 0.4.0 should already have been made >=3.6, because of fsspec

**Comment by fgbocci** [comment]
Ok, so
It will only be supported for Python>=3.6 and the package classifier be updated?

Thanks again

**Comment by martindurant** [comment]
correct

**Comment by TomAugspurger** [comment]
If 3.6 is required, the python_requires should be updated. https://github.com/dask/s3fs/pull/302.

We would also need to update the recipe on conda-forge.

**Comment by TomAugspurger** [comment]
I'm not sure if there's anything to be done for users on 3.5 though, short of pulling the 0.4 package. I think pip will always try to pull 0.4.1.

**Comment by fgbocci** [comment]
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Maybe platform specific markers?

**Comment by TomAugspurger** [comment]
I don't think so. `python_requires` does everything we need, we just have a release where they're set incorrectly.

**Comment by martindurant** [comment]
I was somewhat surprised that `pip install s3fs` on py35 really does get the broken version, as it fetches and installs `fsspec` which has `python_requires>3.5` set. I must be used to conda and consistency checking, sorry.
