### ISSUE TITLE
0.4.1 breaks python 3.5 supports

### ISSUE THREAD

**Issue by Jerral3** [dask/s3fs#304]
Hello !

I have found today that new version 0.4.1 breaks python 3.5 support, because of the introduction of a f-string in the function `_coalesce_version_id`.

If you need any additionnal information please let me know, this is my first time opening an issue.

Anyway, thanks for all the good work, I love s3fs !

**Comment by fgbocci** [comment]
Was open and discussed on issue:
https://github.com/dask/s3fs/issues/301

In my python<3.6 projects I pinned 
`s3fs<0.4.1`
and worked. Hope it helps :)

**Comment by Jerral3** [comment]
Oh sorry, I only checked open issues !
Thanks anyway, and yes, I pinned my version :)
