### ISSUE TITLE
Error reading s3 xlsx file to pandas dataframe in 1.4.1

### ISSUE THREAD

**Issue by AvinashAnad** [dask/s3fs#306]
Received a syntax error while reading a csv and xlsx file from s3 to a pandas dataframe after updating the version to 1.4.1.

![unnamed](https://user-images.githubusercontent.com/6704357/78014645-db846700-7365-11ea-9e54-eba4bcd0cde2.png)

had to downgrade back to version 1.4.0 to get things done...

**Comment by martindurant** [comment]
We are aware that 1.4.1 is incompatible with py35, but have not yet decided what to do about this. ( ref #305 )

**Comment by AvinashAnad** [comment]
Thank you :)
