### ISSUE TITLE
Control access permissions

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#31]
It would be nice to be able to set the public access control level to a bucket or file.  When making a bucket with boto3 we do the following:

    client.create_bucket(Bucket=test_bucket_name, ACL='public-read-write')

It's not clear how to cleanly map these out to a general `chmod` api though.

**Comment by martindurant** [comment]
I avoided this because permissions in s3 are complex. You can, for instance, provide read access to some key(s) to one particular user without changing its global access policy. We could go as far as to set the global (hidden|read-only|read-write) access.

**Comment by mrocklin** [comment]
More of a question than a feature request.  It'd be nice to have, but it
sounds like the effort-to-value effort is high.
