### ISSUE TITLE
S3File object has no attribute closed

### ISSUE THREAD

**Issue by idavydov** [dask/s3fs#313]
Hi,
I'm trying to use s3fs with h5py and get [an error](https://github.com/h5py/h5py/issues/1530).

```python
import s3fs
import h5py
s3 = s3fs.S3FileSystem(...)
with s3.open(url, 'r') as s3file:
    with h5py.File(s3file, 'r') as h5f:
        pass
```

```
AttributeError: 'S3File' object has no attribute 'closed'
```

It seems that underlying cause is the fact that S3File object does not have a `closed` attribute. It's strange that the documentation [mentions](https://s3fs.readthedocs.io/en/latest/api.html) this attribute.

Do you think it might be possible to implement this attribute?

**Comment by martindurant** [comment]
That is odd, the attribute does indeed exist:
```
In [9]: s3.ls('mdtemp-temp')
Out[9]:
['mdtemp-temp/afile',
 'mdtemp-temp/afile.npz',
 'mdtemp-temp/dir',
 'mdtemp-temp/temp.csv']

In [10]: f = s3.open('mdtemp-temp/afile')

In [11]: f.closed
Out[11]: False
```
it is set [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L1038).

**Comment by idavydov** [comment]
@martindurant thanks, I will try with a clean installation and report back. Maybe something broken on my side.

**Comment by idavydov** [comment]
@martindurant I can confirm so the following code works as expected:
```python
with s3.open(url, 'r') as s3file:
    print(s3file.closed)
# output: 
# False
```

So I have no idea what's going on.

**Comment by idavydov** [comment]
Ok, it seems that the problem is reading attributes `s3.open(..., 'r')` I changed the code to following and it seems to work now. Thank you.

```python
with s3.open(url, 'rb') as s3file:
    with h5py.File(s3file, 'r') as h5f:
        pass
```

Not sure the error message is a bug or a known behaviour.
