### ISSUE TITLE
Calling fs.info(path) causes a FileNotFoundError

### ISSUE THREAD

**Issue by nyacg** [dask/s3fs#319]
Hello,

When calling `fs.info` on an S3 path via pyarrow I get a `FIleNotFoundError`. I've tracked the problem down to this line: https://github.com/dask/s3fs/blob/master/s3fs/core.py#L536

It seems it expects `self._ls_from_cache(path)` to return `None` if the path isn't in the cache but instead it throws a `FileNotFoundError`. 

The code:

```python
fs = s3fs.S3FileSystem()
ds = pq.ParquetDataset(str(s3_path), filesystem=fs, partitioning="hive")  # Throws FileNotFoundError
```
However, calling `fs.info` directly works with no problems.
```python
fs.info(s3_path / not_found_file)
```

I don't know if the issue comes from pyarrow or s3fs, but the line of code that causes the error to be thrown is in this repo so I thought I'd ask here first. I have fixed the problem locally by wrapping `self._ls_from_cache(path)` in a `try`/`catch` block so it now effectively returns `None` if the file is not in the cache.

Pip-freeze:
```
botocore==1.16.10
docutils==0.15.2
fsspec==0.7.3
jmespath==0.10.0
numpy==1.18.4
pandas==1.0.3
pyarrow==0.17.0
python-dateutil==2.8.1
pytz==2020.1
s3fs==0.4.2
six==1.14.0
urllib3==1.25.9
```
I have experienced this error on python 3.3.7 and 3.6.8

**Comment by martindurant** [comment]
`_ls_from_cache` *should* raise `FileNotFound` in the case that the relevant directory listing is in the cache, but the file you want isn't in there. Methods that write to S3 using your exiting instance (write, rm, ...) should invalidate the cache, but perhaps the writing is happening from another process/machine? In the case that you know the bucket will be volatile, you can use directory caching that automatically expires or no cache at all 
https://filesystem-spec.readthedocs.io/en/latest/features.html#listings-caching

**Comment by nyacg** [comment]
There shouldn't be any reading or writing of these files as they're just static files in a bucket. If any modifications are done it'll be by pyarrow which (AFAIK) can only access the file via the existing s3fs instance
