### ISSUE TITLE
fs.info() can trigger a bad performance if object  is missing and cause unexpected list_object request.

### ISSUE THREAD

**Issue by philipzhaoTS** [dask/s3fs#320]
Reading through the [fs.info](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L555) codebase. I think the following behavior is undesired if a particular file path is missing.

Examples:
fs.info("s3://mybucket/missingDir/missingFile"). 
This will result the following request
head_object (mybucket/missingDir/missingFile) => 404, [line here](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L538)

list_object(mybucket/missingDir, "/" ) => result an empty [], [line here](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L538)

list_object(mybucket/, "/") => result all the data [line here](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L630)

list_object(mybucke/missingDir/missingFile, "/") => result empty [] [line here](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L542)

list_object(mybucket/missingDir, "/") => result an empty [] [line here](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L630)

Given the following example:
fs.info("s3://mybucket/mydir/missingFile")
head_object (mybucket/mydir/missingFile) => 404
list_object(mybucket/mydir, "/" ) => result some files
list_object(mybucket/mydir/missingFile, "/") => result empty []
list_object(mybucket/mydir, "/") => result some files

Now image if mybucket or mybucket/mydir has a lot of files. Then this list_object will trigger a pagination call and result a lot of list operation.

I think a better implementation should be like:
head_object(mybucket/my_key) # if return 404 then continue
list_object(mybucket/my_key, "/", max_key=1) # to determine whether it is a directory or now.

In my opinion, we don't need to call its parent directory to fetch all its data. I understand there is caching within the fs that it will utilize it. But I think that caching should be used when user explicitly call ls() rather than calling info().

**Comment by martindurant** [comment]
Good point, `info` should give FileNotFound immediately, if the HEAD call fails. The only counterargument I can think for this, is that it's possible that a user only has list and not get access to the bucket - can we detect that case?

> `list_object(mybucket/, "/")`

Couldn't figure out why this call is made.

**Comment by philipzhaoTS** [comment]
S3 will give your accessDenied exception, you can pass that exception to caller. Or you can translate into one of fileSystem's exception.

for list_object(mybucket/, "/"). it is called in here: https://github.com/dask/s3fs/blob/master/s3fs/core.py#L630

L628 will result a list_object(mybucket/missingDir, "/") and it will return empty []
And it will fail L629 if check to list its parent directory, in this case, it will be list_bucket(). See self._ls(). https://github.com/dask/s3fs/blob/master/s3fs/core.py#L496

**Comment by martindurant** [comment]
> S3 will give your accessDenied exception

We want to specifically understand that the HEAD call can fail because the object is missing, but that in some cases, all bucket listing is forbidden.


OK, so `AbstractFileSystem` calls ls on the parent, and for s3fs, ls calls parent too (if first listing was empty). This is obviously not ideal. I would be happy to see a fix.

**Comment by martindurant** [comment]
here:
```
L545                if isinstance(ee, FileNotFoundError):
L546                    return super(S3FileSystem, self).info(path)
```
should probably call `self._ls` directly, to see if the path is a prefix, and return a dictionary info if yes.

**Comment by philipzhaoTS** [comment]
self._ls will also result a huge list request.
For example:
mybucket/foo/ dir has 1million objects or subdirectory. self._ls() will result 1000 list requests with pagination (S3 max-keys is 1000, so 1000*1000 = 1millions). And you probably just need to know whether mybucket/foo/ has any files to determine its type as directory or not. 

IMO, do list_object("mybycket/foo/", "/", max-keys=1) to determine its state.

**Comment by martindurant** [comment]
Yes, that could work. That was the idea behind listing the parent - the path would show as a prefix without having to list it (but this falls down, as you found, when the path doesn't exist).

**Comment by philipzhaoTS** [comment]
@martindurant is this reasonable to be fixed by the next release?

**Comment by martindurant** [comment]
@philipzhaoTS , would you like to contribute? I don't know when I would get to it myself.

**Comment by philipzhaoTS** [comment]
Please let me know when you plan to do a new release. Thanks
