### ISSUE TITLE
S3FileSystem.copy multipart copy error

### ISSUE THREAD

**Issue by jonny-wright** [dask/s3fs#321]
In version 0.4.2, I get this error when copying a 6GB file within the same bucket.

`Write failed: ClientError('An error occurred (InvalidArgument) when calling the UploadPartCopy operation: Range specified is not valid for source object of size: 6403334120')`

If I rollback back to 0.4.0 it works. Look related to the use of multipart copy in later versions.

I have tried different files and different bucket and always get this error.

**Comment by martindurant** [comment]
Please debug the bytes ranges created in [this line](https://github.com/dask/s3fs/blob/master/s3fs/core.py#L916) - perhaps there is an off-by-one error.

**Comment by jonny-wright** [comment]
Yes, it does look like an off-by-one error.

[https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_part_copy](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_part_copy)

CopySourceRange is zero based.
