### ISSUE TITLE
Is reading thread safe?

### ISSUE THREAD

**Issue by tkang007** [dask/s3fs#329]
Hello,
Sorry for asking here for usage question as I cannot find any doc. and search on the stackoverflow.

What is the guide for S3FileSystem object sharing between threads for read and write?
Can we use a S3FileSystem instance in multiple threads, async program for read only?

What is the difference between an instance sharing between thread and creating an instance for each instance?  What is the main purpose of S3FileSystem.current()? 

Hope to add some description for this subject somewhere on the document.  

Regards,
TW

**Comment by martindurant** [comment]
Officially, the botocore session is not thread-safe; in practice, I would doubt you ever notice. s3fs, by default, does not construct a new instance of the filesystem object for the same set of parameters (i.e., the instance is cached and reused), so you will share the session object. You can prevent this behaviour with `skip_instance_cache=True` to the constructor.

Note that I suspect the read-write operations always block, so you probably don't gain anything by using threads. However, https://github.com/intake/filesystem_spec/pull/310 is working on adding async operations (as opposed to threads) to the various fsspec implementations.

**Comment by tkang007** [comment]
Thanks so much, martindurant,

**Comment by martindurant** [comment]
Async is coming soon in #336
