### ISSUE TITLE
S3FileSystem.get() downloads incomplete object after update 

### ISSUE THREAD

**Issue by eeroel** [dask/s3fs#332]
Hi,

**What happened**:
Using `get()` to re-download an object that has been overwritten with a larger object results in an incomplete download.

**What you expected to happen**:
I expect `get` to download the whole object.

**Minimal Complete Verifiable Example**:

```
# Create two files, one containing more data than the other:
echo "foo" > v1 && echo "foobar" > v2
# Copy the smaller file into s3 
aws s3 cp v1 s3://$MY_BUCKET/foo

## At this point, start a Python interpreter, create a S3FileSystem and download the data into a file using `get`

# Now copy the larger file to overwrite the previous one
aws s3 cp v2 s3://$MY_BUCKET/foo

## Using the same S3FileSystem object as above, download the data into a file again
``` 

The file resulting from the latter download contains `foob`.

**Anything else we need to know?**:
Note that this also occurs when reading the data into Pandas using e.g. `read_csv`, without instantiating `S3FileSystem` explicitly.

**Environment**:
- s3fs version: 0.4.2, 0.4.0
- Python version: 3.7.3
- Operating System: OS X, Linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
So, it sounds like the download is using the previous value of the file size, from a cached file listing. You can use `s3.invalidate_cache` to manually control clearing this cache, or indeed there are options on how to cache operated in general (if at all). 

However, I am starting to think that maybe the cache shouldn't be used at all when actually downloading, only when displaying info. It would be reasonable for `get` to work without looking up the size, and for `open` to re-query the size via HEAD_OBJECT every time. I'll leave this issue open and hope to look into it when I have the time. With the coming async work, the cost of the potential extra call will be minimised.

**Comment by martindurant** [comment]
As of #336 , `get` (and `cat`) will not query for the file-size, just download everything
