### ISSUE TITLE
open() does not appear to be passing kwargs

### ISSUE THREAD

**Issue by afrozl** [dask/s3fs#333]
**What happened**:
Unable to read SSE-C encrypted file
**What you expected to happen**:
Read file
**Minimal Complete Verifiable Example**:
```python
import s3fs
s3 = s3fs.S3FileSystem(s3_additional_kwargs={'SSECustomerAlgorithm': 'AES256', 'SSECustomerKey': encryption_key})
s3.exists(filename)
```
**_True_**
```python
with s3.open(filename, 'r') as data:
   ...
```
_**OSError: [Errno 22] The object was stored using a form of Server Side Encryption. The correct parameters must be provided to retrieve the object.**_

- Python version:
3.7.3
- Operating System:
Debian 9
- Install method (conda, pip, source):
pip

**Comment by fcomte** [comment]
`import s3fs
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': 'http://minio.stable.innovation.insee.eu'}, s3_additional_kwargs={'SSECustomerAlgorithm': 'AES256', 'SSECustomerKey': "Ma clef de 32 octets !!!!!!!!!!!"})`

`fs.put('test.txt','s3://tm8enk/test.txt')`

is working because I can read this file from S3 using boto3

`import boto3
import pandas as pd
import io
key="Ma clef de 32 octets !!!!!!!!!!!"
s3 = boto3.client('s3',
                  endpoint_url='http://minio.stable.innovation.insee.eu/')
response = s3.get_object(Bucket='tm8enk',
                            Key='test.txt',
                            SSECustomerKey=key,
                            SSECustomerAlgorithm='AES256')
print(response['Body'].read())`

But using fs.cat or fs.open is not working

`fs.cat('s3://tm8enk/test.txt')`

**Comment by martindurant** [comment]
What is your s3fs version, please?

**Comment by fcomte** [comment]
I tried 0.4.2 and 0.4.0 with the same behaviour

**Comment by martindurant** [comment]
I assume [this test](https://github.com/dask/s3fs/blob/master/s3fs/tests/test_s3fs.py#L909) fails for you on real S3? What if you instantiate as `S3FileSystem(s3_additional_kwargs={'ServerSideEncryption': 'AES256', ... ?})`

Given #336 , I may ask you to wait a bit until that large rewrite has been merged before I track this down.

**Comment by fcomte** [comment]
This test fail with SSE-C

```
import s3fs
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': 'http://minio.stable.innovation.insee.eu'}, s3_additional_kwargs={'SSECustomerAlgorithm': 'AES256', 'SSECustomerKey': "Ma clef de 32 octets !!!!!!!!!!!"})
```

In fact this is very strange :

```
with fs.open('tm8enk/test', 'wb') as f:
    f.write(b'hello toto')
```

is perfectly working and the file tm8enk/test is encrypted and contain 'hello toto' if i read it with boto3

but cat is failing

**Comment by martindurant** [comment]
OK, thanks for investigating - I'll get back to you.
(ping me if you don't hear anything)

**Comment by fcomte** [comment]
a last test : 

```
import s3fs
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': 'http://minio.stable.innovation.insee.eu'}, s3_additional_kwargs={'SSECustomerAlgorithm': 'AES256', 'SSECustomerKey': "Ma clef de 32 octets !!!!!!!!!!!"})
```


```
with fs.open('tm8enk/blabla.csv', 'rb') as f:
    print(f.read())
```

work because blabla.csv is not encrypted.

```
with fs.open('tm8enk/test', 'rb') as f:
    print(f.read())
```

does not work because test is uncrypted.
Everything is like , encryption http headers are not sent to S3 storage for read access.

**Comment by martindurant** [comment]
Now that async is in, would you like to try fixing this to pass the args through, @afrozl ?

**Comment by martindurant** [comment]
ditto @fcomte :)

**Comment by fcomte** [comment]
I am not able to do that, I am sorry

**Comment by fcomte** [comment]
@martindurant do toi have any Idea how to resolv that?

**Comment by martindurant** [comment]
Appears to be working with 0.5.0
```python
s3 = s3fs.S3FileSystem(s3_additional_kwargs={'SSECustomerAlgorithm': 'AES256', 'SSECustomerKey': "Ma clef de 32 octets !!!!!!!!!!!"})
with s3.open('mybucket/mykey', 'wb') as f:
    f.write(b'data)
with s3.open('mybucket/mykey', 'rb') as f:
    r.read() == b'data'
s3.cat('mybucket/mykey') == b'data'
S3FileSystem().cat('mybucket/mydata')  # no SSE, OSError 22
```

Please verify

**Comment by fcomte** [comment]
It's true. It works with 0.5.0
Thx
