### ISSUE TITLE
Working example of using Async/Await

### ISSUE THREAD

**Issue by franz101** [dask/s3fs#340]
Is it possible to give one or two examples on how to use s3fs async await?

```python
import asyncio
import aiobotocore

async def runner():
    s3 = s3fs.core.S3FileSystem(session=aiobotocore.AioSession(profile="test"))
    d = s3.open('s3://test-dev/dev/2020_test.json', 'rb').read()
    return  d


loop = asyncio.get_event_loop()
response = loop.run_until_complete(runner())

print(response)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-a9b2eb071b6d> in <module>
     12 
     13 loop = asyncio.get_event_loop()
---> 14 response = loop.run_until_complete(runner())
     15 
     16 print(response)

/usr/local/anaconda3/lib/python3.7/site-packages/nest_asyncio.py in run_until_complete(self, future)
     57         if not f.done():
     58             raise RuntimeError('Event loop stopped before Future completed.')
---> 59         return f.result()
     60 
     61     def _run_once(self):

/usr/local/anaconda3/lib/python3.7/asyncio/futures.py in result(self)
    179         self.__log_traceback = False
    180         if self._exception is not None:
--> 181             raise self._exception
    182         return self._result
    183 

/usr/local/anaconda3/lib/python3.7/asyncio/tasks.py in __step(***failed resolving arguments***)
    247                 # We use the `send` method directly, because coroutines
    248                 # don't have `__iter__` and `__next__` methods.
--> 249                 result = coro.send(None)
    250             else:
    251                 result = coro.throw(exc)

<ipython-input-21-a9b2eb071b6d> in runner()
      7 async def runner():
      8     s3 = s3fs.core.S3FileSystem(session=aiobotocore.AioSession(profile="franz"))
----> 9     d = s3.open('s3://data-world-dev/dev/2020_straight_1843.json', 'rb').read()
     10     return  d
     11 

/usr/local/anaconda3/lib/python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    842                 autocommit=ac,
    843                 cache_options=cache_options,
--> 844                 **kwargs
    845             )
    846             if not ac:

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in _open(self, path, mode, block_size, acl, version_id, fill_cache, cache_type, autocommit, requester_pays, **kwargs)
    392                       version_id=version_id, fill_cache=fill_cache,
    393                       s3_additional_kwargs=kw, cache_type=cache_type,
--> 394                       autocommit=autocommit, requester_pays=requester_pays)
    395 
    396     async def _lsdir(self, path, refresh=False, max_items=None):

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in __init__(self, s3, path, mode, block_size, acl, version_id, fill_cache, s3_additional_kwargs, autocommit, cache_type, requester_pays)
   1274         self.req_kw = {'RequestPayer': 'requester'} if requester_pays else {}
   1275         super().__init__(s3, path, mode, block_size, autocommit=autocommit,
-> 1276                          cache_type=cache_type)
   1277         self.s3 = self.fs  # compatibility
   1278         if self.writable():

/usr/local/anaconda3/lib/python3.7/site-packages/fsspec/spec.py in __init__(self, fs, path, mode, block_size, autocommit, cache_type, cache_options, **kwargs)
   1132         if mode == "rb":
   1133             if not hasattr(self, "details"):
-> 1134                 self.details = fs.info(path)
   1135             self.size = self.details["size"]
   1136             self.cache = caches[cache_type](

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in info(self, path, version_id, refresh)
    717 
    718         if should_fetch_from_s3:
--> 719             return sync(self.loop, self._info, path, bucket, key, kwargs, version_id)
    720         return super().info(path)
    721 

/usr/local/anaconda3/lib/python3.7/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     49     if error[0]:
     50         typ, exc, tb = error[0]
---> 51         raise exc.with_traceback(tb)
     52     else:
     53         return result[0]

/usr/local/anaconda3/lib/python3.7/site-packages/fsspec/asyn.py in f()
     33             if callback_timeout is not None:
     34                 future = asyncio.wait_for(future, callback_timeout)
---> 35             result[0] = await future
     36         except Exception:
     37             error[0] = sys.exc_info()

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in _info(self, path, bucket, key, kwargs, version_id)
    658         try:
    659             out = await self._call_s3(self.s3.head_object, kwargs, Bucket=bucket,
--> 660                                       Key=key, **version_id_kw(version_id), **self.req_kw)
    661             return {
    662                 'ETag': out['ETag'],

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in _call_s3(self, method, *akwarglist, **kwargs)
    213                 err = e
    214                 break
--> 215         raise translate_boto_error(err)
    216 
    217     call_s3 = sync_wrapper(_call_s3)

/usr/local/anaconda3/lib/python3.7/site-packages/s3fs/core.py in _call_s3(self, method, *akwarglist, **kwargs)
    206         for i in range(self.retries):
    207             try:
--> 208                 return await method(**additional_kwargs)
    209             except S3_RETRYABLE_ERRORS as e:
    210                 err = e

/usr/local/anaconda3/lib/python3.7/site-packages/aiobotocore/client.py in _make_api_call(self, operation_name, api_params)
    119         else:
    120             http, parsed_response = await self._make_request(
--> 121                 operation_model, request_dict, request_context)
    122 
    123         await self.meta.events.emit(

/usr/local/anaconda3/lib/python3.7/site-packages/aiobotocore/client.py in _make_request(self, operation_model, request_dict, request_context)
    138     async def _make_request(self, operation_model, request_dict, request_context):
    139         try:
--> 140             return await self._endpoint.make_request(operation_model, request_dict)
    141         except Exception as e:
    142             await self.meta.events.emit(

/usr/local/anaconda3/lib/python3.7/site-packages/aiobotocore/endpoint.py in _send_request(self, request_dict, operation_model)
     88         while await self._needs_retry(attempts, operation_model,
     89                                       request_dict, success_response,
---> 90                                       exception):
     91             attempts += 1
     92             # If there is a stream associated with the request, we need

/usr/local/anaconda3/lib/python3.7/site-packages/aiobotocore/endpoint.py in _needs_retry(self, attempts, operation_model, request_dict, response, caught_exception)
    192             event_name, response=response, endpoint=self,
    193             operation=operation_model, attempts=attempts,
--> 194             caught_exception=caught_exception, request_dict=request_dict)
    195         handler_response = first_non_none_response(responses)
    196         if handler_response is None:

/usr/local/anaconda3/lib/python3.7/site-packages/aiobotocore/hooks.py in _emit(self, event_name, kwargs, stop_on_response)
     27                 response = await handler(**kwargs)
     28             else:
---> 29                 response = handler(**kwargs)
     30 
     31             responses.append((handler, response))

/usr/local/anaconda3/lib/python3.7/site-packages/botocore/utils.py in redirect_from_error(self, request_dict, response, operation, **kwargs)
   1209         bucket = request_dict['context']['signing']['bucket']
   1210         client_region = request_dict['context'].get('client_region')
-> 1211         new_region = self.get_bucket_region(bucket, response)
   1212 
   1213         if new_region is None:

/usr/local/anaconda3/lib/python3.7/site-packages/botocore/utils.py in get_bucket_region(self, bucket, response)
   1267         try:
   1268             response = self._client.head_bucket(Bucket=bucket)
-> 1269             headers = response['ResponseMetadata']['HTTPHeaders']
   1270         except ClientError as e:
   1271             headers = e.response['ResponseMetadata']['HTTPHeaders']

TypeError: 'coroutine' object is not subscriptable

**Comment by martindurant** [comment]
The async functionality has not yet appeared in a. release - but an async test and documentation would be a good idea. [This](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/tests/test_http.py#L230) in the fsspec test suite would be a good place to start.

**Comment by martindurant** [comment]
A test was added in #341

**Comment by martindurant** [comment]
Doc update https://s3fs.readthedocs.io/en/latest/#async
