### ISSUE TITLE
In version 0.5.0 writing a file to an existing folder in an existing S3 bucket from Sagemaker fails with Access Denied

### ISSUE THREAD

**Issue by DannyVarod** [dask/s3fs#346]
**What happened**: Accessed Denied
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
~/anaconda3/envs/python3/lib/python3.6/site-packages/s3fs/core.py in _mkdir(self, path, acl, create_parents, **kwargs)
    445                     }
--> 446                 await self.s3.create_bucket(**params)
    447                 self.invalidate_cache('')

~/anaconda3/envs/python3/lib/python3.6/site-packages/aiobotocore/client.py in _make_api_call(self, operation_name, api_params)
    133             error_class = self.exceptions.from_code(error_code)
--> 134             raise error_class(parsed_response, operation_name)
    135         else:

ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

The above exception was the direct cause of the following exception:

PermissionError                           Traceback (most recent call last)
<ipython-input-4-87e4a26a1823> in <module>
----> 1 data.to_csv(folder + output_file)

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/generic.py in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal, errors)
   3163             doublequote=doublequote,
   3164             escapechar=escapechar,
-> 3165             decimal=decimal,
   3166         )
   3167         formatter.save()

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py in __init__(self, obj, path_or_buf, sep, na_rep, float_format, cols, header, index, index_label, mode, encoding, errors, compression, quoting, line_terminator, chunksize, quotechar, date_format, doublequote, escapechar, decimal)
     65 
     66         self.path_or_buf, _, _, self.should_close = get_filepath_or_buffer(
---> 67             path_or_buf, encoding=encoding, compression=compression, mode=mode
     68         )
     69         self.sep = sep

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/io/common.py in get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    231                 storage_options["anon"] = True
    232             file_obj = fsspec.open(
--> 233                 filepath_or_buffer, mode=mode or "rb", **(storage_options or {})
    234             ).open()
    235 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/core.py in open(urlpath, mode, compression, encoding, errors, protocol, newline, **kwargs)
    397         newline=newline,
    398         expand=False,
--> 399         **kwargs
    400     )[0]
    401 

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/core.py in open_files(urlpath, mode, compression, encoding, errors, name_function, num, protocol, newline, auto_mkdir, expand, **kwargs)
    252     if "r" not in mode and auto_mkdir:
    253         parents = {fs._parent(path) for path in paths}
--> 254         [fs.makedirs(parent, exist_ok=True) for parent in parents]
    255     return OpenFiles(
    256         [

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/core.py in <listcomp>(.0)
    252     if "r" not in mode and auto_mkdir:
    253         parents = {fs._parent(path) for path in paths}
--> 254         [fs.makedirs(parent, exist_ok=True) for parent in parents]
    255     return OpenFiles(
    256         [

~/anaconda3/envs/python3/lib/python3.6/site-packages/s3fs/core.py in makedirs(self, path, exist_ok)
    458 
    459     def makedirs(self, path, exist_ok=False):
--> 460         self.mkdir(path, create_parents=True)
    461 
    462     async def _rmdir(self, path):

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
     98     def wrapper(*args, **kwargs):
     99         self = obj or args[0]
--> 100         return maybe_sync(func, self, *args, **kwargs)
    101 
    102     return wrapper

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/asyn.py in maybe_sync(func, self, *args, **kwargs)
     78         if inspect.iscoroutinefunction(func):
     79             # run the awaitable on the loop
---> 80             return sync(loop, func, *args, **kwargs)
     81         else:
     82             # just call the blocking function

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/asyn.py in sync(loop, func, callback_timeout, *args, **kwargs)
     49     if error[0]:
     50         typ, exc, tb = error[0]
---> 51         raise exc.with_traceback(tb)
     52     else:
     53         return result[0]

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/asyn.py in f()
     33             if callback_timeout is not None:
     34                 future = asyncio.wait_for(future, callback_timeout)
---> 35             result[0] = await future
     36         except Exception:
     37             error[0] = sys.exc_info()

~/anaconda3/envs/python3/lib/python3.6/site-packages/s3fs/core.py in _mkdir(self, path, acl, create_parents, **kwargs)
    448                 self.invalidate_cache(bucket)
    449             except ClientError as e:
--> 450                 raise translate_boto_error(e) from e
    451             except ParamValidationError as e:
    452                 raise ValueError('Bucket create failed %r: %s' % (bucket, e))

PermissionError: Access Denied

**What you expected to happen**:

File created, no exception.

**Minimal Complete Verifiable Example**:

```python
!pip install --upgrade s3fs==0.5.0  # works when replaced with 0.4.2

import pandas

folder = 's3://my-bucket/my-folder/'
input_file = 'small.csv'
output_file = 'new.csv'  # file should not exist prior to test
data = pandas.read_csv(folder + input_file)
data.to_csv(folder + output_file)
```

**Anything else we need to know?**: I initially tried increasing access, to no effect

**Environment**: S3 notebook (sagemaker)

- Dask version:
- Python version: 3
(Recreated with various kernel options in notebook e.g. conda_python3)
- Operating System:
- Install method (conda, pip, source): !pip install --upgrade s3fs==0.5.0  # works with 0.4.2

**Comment by martindurant** [comment]
Ah, `fsspec` calls a slightly different code path to s3 itself. Would you mind trying with the following diff
```diff
--- a/s3fs/core.py
+++ b/s3fs/core.py
@@ -431,7 +431,7 @@ class S3FileSystem(AsyncFileSystem):
     async def _mkdir(self, path, acl="", create_parents=True, **kwargs):
         path = self._strip_protocol(path).rstrip('/')
         bucket, key, _ = self.split_path(path)
-        if not key or create_parents:
+        if not key or (create_parents and not await self.exists(bucket)):
             # catch error if creating existing bucket?
```

(my apologies, a lot changed in this series of releases)

**Comment by martindurant** [comment]
(better still, please check the linked PR @DannyVarod )
