### ISSUE TITLE
Cannot import name 'SSOProvider' from 'botocore.credentials' in 0.50

### ISSUE THREAD

**Issue by meneal** [dask/s3fs#348]
**What you expected to happen**:

```python
$ python
>>> import s3fs
>>>
```

**What happened**:

```python
$ python
>>> import s3fs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/usr/local/lib/python3.7/site-packages/s3fs/core.py", line 14, in <module>
    import aiobotocore
  File "/usr/local/lib/python3.7/site-packages/aiobotocore/__init__.py", line 1, in <module>
    from .session import get_session, AioSession
  File "/usr/local/lib/python3.7/site-packages/aiobotocore/session.py", line 11, in <module>
    from .credentials import create_credential_resolver, AioCredentials
  File "/usr/local/lib/python3.7/site-packages/aiobotocore/credentials.py", line 15, in <module>
    from botocore.credentials import EnvProvider, Credentials, RefreshableCredentials, \
ImportError: cannot import name 'SSOProvider' from 'botocore.credentials' (/home/airflow/.local/lib/python3.7/site-packages/botocore/credentials.py)
```

**Environment**:

```python
aiobotocore==1.1.0
boto3==1.12.26
botocore==1.15.26
s3fs==0.5.0
```

- Dask version: 0.5.0
- Python version: 3.7.7
- Operating System: Debian Buster
- Install method (conda, pip, source): pip

**Comment by meneal** [comment]
I believe this is caused by: https://github.com/aio-libs/aiobotocore/issues/824

**Comment by martindurant** [comment]
It sounds like you can solve this by downgrading. I tested with aiobotocore 1.0.7 locally. v1.1.0 is less than a week old.

**Comment by meneal** [comment]
>It sounds like you can solve this by downgrading. I tested with aiobotocore 1.0.7 locally. v1.1.0 is less than a week old.

@martindurant 
Does it make sense to pin the version [here](https://github.com/dask/s3fs/blob/master/requirements.txt#L1)? If so, I am happy to submit a PR.

**Comment by meneal** [comment]
It looks like this is on my end as I mentioned here: https://github.com/aio-libs/aiobotocore/issues/824#issuecomment-679188851 Closing.
