### ISSUE TITLE
Q: How to control read & write cache size limit ?

### ISSUE THREAD

**Issue by tkang007** [dask/s3fs#349]
Hello,

Many thanks to s3fs contributors and very sorry for asking here. 

I think s3fs might have option for fsspec maxblocks option to control cache size limit,  but I cannot find  a clue at doc and source code.  
Is there any way to control max read and write cache size limit? 

Actually, I have an OOM killed issue when using s3fs 0.4.2, python 3.6.9, , concurrent.futures.ProcessPoolExecutor.map()  at RedHat system. 

I have applied below options, but OOM killed issued was not resolved.
```
    kws3fs = {
        #- instance cache
        "skip_instance_cache": False,   # default False.  True to force creating a new instance even if a matching instance exists.

        #- listing cache
        "use_listings_cache": True,     # default True. lsdir caching
        "listings_expiry_time": 60,     # default None for no expiry. seconds of  LRU caching for max_paths
        "max_paths": 128,               # defult None as listings_expiry_time is None. set 512 lists

        #- file read & write cache
        #"default_block_size": 5 * 1024 * 1024,  # deafult 5MB.  blocksize for read & write caching. fsspec maxblocks for limit cache size, how to set at s3fs?

        #- cache type: Set to “none” if no caching is desired. OOM case, https://github.com/dask/s3fs/issues/234
        "default_cache_type": 'none',  
        #- note: s3fs 0.4.2, fspec 0.8.0: default_cache_type='none'  might not properly worked  OOM case when using a little larger chunksize.
        "default_fill_cache": False,
    }
```

Thanks,
TK.

**Comment by martindurant** [comment]
The blocksize determined how much data is kept in memory by the file instance after passing data to the caller. If, however, you are issuing commands file `f.read(big_number)`, then you will still have high memory usage, if there are many bytes available. Therefore, it might depend on how you are interacting with the files. Can you figure out where memory is being used up? Perhaps the stacktrace of the OOM is useful.

**Comment by tkang007** [comment]
Hello Martindurant,  Many thanks for your input. I will try to profile memory usage and will comment here for any findings.

**Comment by tkang007** [comment]
Hi,
Not sure where is memory leak, but catch tracemalloc output as an example and share at blow.

I imagine many text lines(1+ million) converting to dataclass converting stream processing (include decompression) might cause memory fragmentation and can consumed 30+% system memory in a 1 cpu, 2 GB memory system.  

The minimum and default block_size is 5MB,  it looks like a little large for compressed file and can consume 20+MB memory (4 times of compressed size) for a block processing.  

```
=tracemalloc=  top 10 display
Top 10 lines
#1: <frozen importlib._bootstrap_external>:487: 20625.7 KiB
#2: /usr/lib/python3.6/json/decoder.py:355: 3898.9 KiB
    obj, end = self.scan_once(s, idx)
#3: /usr/lib/python3.6/abc.py:133: 854.6 KiB
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
#4: /usr/lib/python3.6/collections/__init__.py:429: 589.9 KiB
    exec(class_definition, namespace)
#5: /usr/lib/python3.6/linecache.py:137: 511.6 KiB
    lines = fp.readlines()
#6: /mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/asn1crypto/parser.py:232: 448.6 KiB
    encoded_data[pointer:contents_end],
#7: /mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/pycparser/yacctab.py:16: 415.0 KiB
    _lr_action[_x][_k] = _y
#8: /mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:93: 414.9 KiB
    setattr(conditional_lib, attr, getattr(lib, attr))
#9: <frozen importlib._bootstrap_external>:60: 283.7 KiB
#10: /usr/lib/python3.6/_weakrefset.py:37: 274.2 KiB
    self.data = set()
29037 other: 21382.4 KiB
Total allocated size: 49699.7 KiB

=tracemalloc=  top 1 traceback
20101 memory blocks: 2008.4 KiB
  File "/usr/lib/python3.6/json/decoder.py", line 355
    obj, end = self.scan_once(s, idx)
  File "/usr/lib/python3.6/json/decoder.py", line 339
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/__init__.py", line 367
    return cls(**kw).decode(s)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/loaders.py", line 175
    return json.loads(payload, object_pairs_hook=OrderedDict)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/loaders.py", line 420
    found = self.file_loader.load_file(possible_path)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/loaders.py", line 132
    data = func(self, *args, **kwargs)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/session.py", line 160
    endpoints = loader.load_data('endpoints')
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/session.py", line 919
    self._components[name] = factory()
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/session.py", line 697
    return self._internal_components.get_component(name)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/botocore/session.py", line 824
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/s3fs/core.py", line 293
    **self.client_kwargs)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/s3fs/core.py", line 187
    self.s3 = self.connect()
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/fsspec/spec.py", line 55
    obj = super().__call__(*args, **kwargs)
  File "/mnt/c/projectg/sfgtl/sfgtl/s3com.py", line 87
    sfs = s3fs.S3FileSystem(anon=False, **kws3fs)
  File "/mnt/c/projectg/sfgtl/sfgtl/scan.py", line 285
    sfs = s3com.make_sfs()
  File "/mnt/c/projectg/sfgtl/sfgtl/check.py", line 121
    limit=limit)
  File "/mnt/c/projectg/sfgtl/sfgtl/gate.py", line 90
    for acheck in itcheck:
  File "/mnt/c/projectg/sfgtl/sfgtl/form.py", line 106
    for agate in itgate:
  File "/mnt/c/projectg/sfgtl/sfgtl/load.py", line 71
    for aform in itform:
  File "/mnt/c/projectg/sfgtl/sfgtl/load.py", line 118
    for aload in itload:
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/click/decorators.py", line 21
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/click/core.py", line 610
    return callback(*args, **kwargs)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/click/core.py", line 1066
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/click/core.py", line 1259
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/projectg/sfgtl/.venv-linux/lib/python3.6/site-packages/click/core.py", line 782
    rv = self.invoke(ctx)
```

Thanks,
TK

**Comment by martindurant** [comment]
A few times the data size seems reasonable to me - you have the original compressed bytes in the HTTP stream, data bytes, some slicing to get specific ranges, conversion to text (needed by JSON) and set of objects being built by JSON.

In your own code, you may be able to figure out where the read is happening.

The 5MB standard in the library comes from wanting to reduce the fraction of time spent establishing connections - there is a time overhead for each call, so you generally want to fetch as man bytes as to make that call worthwhile.

**Comment by tkang007** [comment]
Thanks for your comment and will close this case. 
I have  reduced concurrent.futures.ProcessPoolExecutor.map, chunksize=1 and  line-by-line converting chunking size=0.5MB  from 1MB for small system to reducing  OOM killed cases.
Thanks. TK.

**Comment by tkang007** [comment]
Hello,
When I use fileobj.flush()  periodically, OOM issue was not happened and process memory was not increased continuously.

As the fsspec flush doc:  Write buffered data to backend store. Writes the current buffer, if it is larger than the block-size.

Thanks.
TK

**Comment by tkang007** [comment]
Hello,

I have identify root cause of this case, it was caused by my code when using itertools.tee to split a big data file at small system.  

It was resolved by implementing flow controlled, locked tee to balance data consuming in between iter tee objects.

Detail code for this implementation can be found here, https://stackoverflow.com/questions/6703594/is-the-result-of-itertools-tee-thread-safe-python/63636352#63636352

Thanks,
TK.
