### ISSUE TITLE
s3fs not installing properly

### ISSUE THREAD

**Issue by neerajabhamidipati** [dask/s3fs#355]
**What happened**: s3fs does not install properly. ModuleNotFoundError when I import s3fs in python. The error seems to have to do with bootcore: `ERROR: awscli 1.18.130 has requirement botocore==1.17.53, but you'll have botocore 1.17.54 which is incompatible.`

**What you expected to happen**: install s3fs successfully without any errors when I try `pip install s3fs`.

**Minimal Complete Verifiable Example**: `pip install s3fs`

```python
import s3fs
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 
- Python version: 2.7.13
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
s3fs has not been released for py2 for a while now. You may be able to pin to specific old versions to make it work.

**Comment by neerajabhamidipati** [comment]
Thanks! Loading python3 made it work.
