### ISSUE TITLE
0.5.1 Using s3fs with multiprocessing and pandas.read_csv hangs under certain conditions

### ISSUE THREAD

**Issue by bradenkinard** [dask/s3fs#369]
I have many csv files that are stored in s3 that I use as part of a pytorch pipeline. As part of the pipeline, I iterate through each of the files using pandas' read_csv function to fit some preprocessing transformers, and then I later use a custom Pytorch dataset/dataloader to feed data to the model itself. This process worked fine until a few weeks ago, when I found that the process of iterating through the data loader would hang immediately if the following was true:

- s3fs version >= 0.5.0 (0.4.2 and below works)
- I used 2 or more workers in the data loader (0 or 1 worker works even for 0.5.0)
- I had already iterated through the files using s3fs/pandas during the preprocessing step (works if I skip the preprocessing iteration and go straight to the data loader)

I further tried to determine if the issue was related to pandas, pytorch, or s3fs. I found that my version of s3fs had switched at some point from 0.4.2 to 0.5.1, which seems to be causing the issue: reverting to 0.4.2 makes everything work again. Additionally process works normally when executing on csv files held locally, when pandas isn't using s3fs to read in the files.

I also looked into possibilities of shared memory problems, the size of the csv files, and the number of files, none of which seemed to be influencing the behavior.

**What you expected to happen**:
The following works for s3fs 0.4.2 for all values of NUM_WORKERS. Under 0.5.0 and above, if NUM_WORKERS >= 2, and the preprocessing block is run, it hangs immediately for the pytorch dataloader block. It also works if the csv filepaths point to the local machine, and therefore s3fs is not used. For the sake of clarity and conciseness, I've stripped out the actual preprocessing and simply loop through the files.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import torch
from torch.utils.data import IterableDataset, ChainDataset, DataLoader


# Pytorch csv iterable dataset
class CsvDataset(IterableDataset):
    def __init__(self, filename):
        self.filename = filename

    def __iter__(self):
        data = pd.read_csv(self.filename).values.tolist()
        for line in data:
            yield line

# Iterable dataset for multiple csv files
class MultiCsvDataset(IterableDataset):
    def __init__(self, file_list):
        self.file_list = file_list

    def __iter__(self):
        # Logic for dividing files between multiple workers
        file_list = self.file_list
        worker = torch.utils.data.get_worker_info()
        worker_id = worker.id if worker is not None else -1
        n_workers = worker.num_workers if worker is not None else 0
        if worker:
            file_list = file_list[worker_id::n_workers]

        # Dataset that iterates through chained csv files
        datasets = [CsvDataset(key) for key in file_list]
        dataset = ChainDataset(datasets)

        for line in dataset:
            yield line


KEYS = ["s3://my-bucket/file1.csv", "s3://my-bucket/file2.csv"]
NUM_WORKERS = 2  # Works if 0 or 1, hangs if >= 2
RUN_PREPROCESSING_BLOCK = True

# Preprocessing block (runs, but causes the next block to hang. If skipped, the next block runs fine)
if RUN_PREPROCESSING_BLOCK:
    i = 1
    for key in KEYS:
        pd.read_csv(key)
        print(f"File {i} successful")
        i += 1

# Pytorch dataloader block (works if preprocessing block has not been run, or if NUM_WORKERS < 2,
# or if s3fs version is <= 0.4.2, otherwise hangs indefinitely on the first batch)
dataset = MultiCsvDataset(KEYS)
loader = DataLoader(dataset, batch_size=10, num_workers=NUM_WORKERS)
i = 1
for batch in loader:
    print(f"Batch {i} successful")
    i += 1
```

**Anything else we need to know?**:

**Environment**:

- s3fs version: 0.5.1
- Python version: 3.7.7
- Operating System: MacOS, also Linux Docker container
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Thanks for the report. 
Do you know if multiprocessing works by fork (i.e., you get a copy of the memory in the child processes) or spawn (i.e., you get a new process, and objects are sent by pickle)? Could you try with the other method for starting processes? See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods It seems to me that spawn and forkserver work OK, but fork (default on linux) does not. 

> Pytorch dataloader block (works if preprocessing block has not been run

Would you mind running `s3.clear_instance_cache()` in the main process, or instantiate with `S3FileSystem(..., skip_instance_cache=True)` in the child processes?

**Comment by martindurant** [comment]
PS: thanks for the clear report and investigation.

**Comment by martindurant** [comment]
I am contemplating the following check (which would still not work when attempting to reuse the same s3 instance)
```diff
--- a/fsspec/spec.py
+++ b/fsspec/spec.py
@@ -39,6 +39,7 @@ class _Cached(type):
         # collecting instances when all other references are gone. To really
         # delete a FileSystem, the cache must be cleared.
         cls._cache = {}
+        cls._pid = os.getpid()

     def __call__(cls, *args, **kwargs):
         extra_tokens = tuple(
@@ -46,6 +47,9 @@ class _Cached(type):
         )
         token = tokenize(cls, *args, *extra_tokens, **kwargs)
         skip = kwargs.pop("skip_instance_cache", False)
+        if os.getpid() != cls._pid:
+            cls._cache.clear()
+            cls._pid = os.getpid()
         if not skip and cls.cachable and token in cls._cache:
             return cls._cache[token]
```

**Comment by bradenkinard** [comment]
Indeed, the default behavior for the data loader is fork (at least on the unix machines I've been using). Switching the method to spawn results in the process running correctly with no hangs. (Note that it appears that trying to change the start method default behavior outside of a `"__name__ "== "__main__"` block causes problems).

```
import pandas as pd
import torch
from torch.utils.data import IterableDataset, ChainDataset, DataLoader


# Pytorch csv iterable dataset
class CsvDataset(IterableDataset):
    def __init__(self, filename):
        self.filename = filename

    def __iter__(self):
        data = pd.read_csv(self.filename).values.tolist()
        for line in data:
            yield line


# Iterable dataset for multiple csv files
class MultiCsvDataset(IterableDataset):
    def __init__(self, file_list):
        self.file_list = file_list

    def __iter__(self):
        # Logic for dividing files between multiple workers
        file_list = self.file_list
        worker = torch.utils.data.get_worker_info()
        worker_id = worker.id if worker is not None else -1
        n_workers = worker.num_workers if worker is not None else 0
        if worker:
            file_list = file_list[worker_id::n_workers]

        # Dataset that iterates through chained csv files
        datasets = [CsvDataset(key) for key in file_list]
        dataset = ChainDataset(datasets)

        for line in dataset:
            yield line


if __name__ == "__main__":
    torch.multiprocessing.set_start_method("spawn") # Works if 'spawn', 'fork fails
    KEYS = ["s3://my-bucket/file1.csv", "s3://my-bucket/file2.csv"]
    NUM_WORKERS = 2  # Works if 0 or 1, hangs if >= 2
    RUN_PREPROCESSING_BLOCK = True

    # Preprocessing block (works in all cases)
    if RUN_PREPROCESSING_BLOCK:
        i = 1
        for key in KEYS:
            pd.read_csv(key)
            print(f"File {i} successful")
            i += 1

    # Pytorch dataloader block (works if preprocessing block has not been run, or if NUM_WORKERS < 2,
    # or if s3fs version is <= 0.4.2, otherwise hangs indefinitely on the first batch)
    dataset = MultiCsvDataset(KEYS)
    loader = DataLoader(dataset, batch_size=10, num_workers=NUM_WORKERS)
    i = 1
    for batch in loader:
        print(f"Batch {i} successful")
        i += 1
```
