### ISSUE TITLE
Fast clear

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#40]
Clearing many keys from a single bucket has become a somewhat frequent operation.  Currently we do this by cycling through all of the keys one-by-one and removing them.  Is there a bulk remove-many or remove-bucket operation in boto3 that we can do instead ?

**Comment by mrocklin** [comment]
This may be useful

http://stackoverflow.com/a/34888103/616616

```python
s3 = boto3.resource('s3')
objects_to_delete = s3.meta.client.list_objects(Bucket="MyBucket", Prefix="myfolder/test/")

delete_keys = {'Objects' : []}
delete_keys['Objects'] = [{'Key' : k} for k in [obj['Key'] for obj in objects_to_delete.get('Contents', [])]]

s3.meta.client.delete_objects(Bucket="MyBucket", Delete=delete_keys)
```

**Comment by mrocklin** [comment]
Verified.  In practice that is 100x faster.

**Comment by martindurant** [comment]
Ah yes, seen it - easy to implement too (up to 1000 keys per call). And this is on the client object used by S3FileSystem, no need to touch the boto3 resource. Should be used for rm, recursive?
I can implement it tomorrow.

**Comment by mrocklin** [comment]
Great.  Question: are there other bulk operations like this that we should be aware of?

**Comment by martindurant** [comment]
Nothing I can see: here under Batch Actions http://boto3.readthedocs.org/en/latest/guide/collections.html#
The only method I can spot of possible interest in the client is `upload_file`, not sure if this does things differently than the put methods I'm using.
