### ISSUE TITLE
version_id is None when writing empty object to S3

### ISSUE THREAD

**Issue by matteofigus** [dask/s3fs#402]
**What happened**:
When I use s3fs to write a file to s3, it doesn't return its version id if the object is empty. The object is correctly written.

**What you expected to happen**:
It should return its version id, similar to what happens with similar call done with boto3

**Minimal Complete Verifiable Example**:

```python
import s3fs

s3 = s3fs.S3FileSystem(
    default_cache_type="none",
    requester_pays=True,
    default_fill_cache=False,
    version_aware=True
)

with s3.open("s3://bucket/test1.json", "wb") as f:
    #f.write(b'{"a":1}\n') <= no problem if I write some content
    f.write(b'') # <= if I write this, f.version_id is None

print(f.version_id)
# I tried to invalidate the cache...no difference both for success and failure scenarios
s3.invalidate_cache()
print(f.version_id)
```

**Anything else we need to know?**:

**Environment**: 

- Python version: 3.7.5
- Operating System: tried MacOS and Linux
- Install method (conda, pip, source): tried pip 0.4.0, 0.5.0, 0.5.1 and source (latest commit)

**Comment by martindurant** [comment]
cc @mariusvniekerk , if you've come across this before.
