### ISSUE TITLE
Exists check fails starting from version 0.5.1 on OpenStack Object Storage ("Swift")

### ISSUE THREAD

**Issue by totycro** [dask/s3fs#404]
**What happened**:
When using s3fs 0.5.1 or 0.5.2, I get the following error when triggering an "exists" check for example using `in` when accesing the Object Storage of the Open Telekom Cloud, which is an OpenStack deployment. It seems to not feature the key `KeyCount`, and i'm not sure if the problem is rather in s3fs or in the server implementation.  
However I found it noteworthy that this problem doesn't seem to occur with s3fs 0.5.0. 
```
  File "read_bucket.py", line 7, in <module>
    print('a' in store)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/fsspec/mapping.py", line 169, in __contains__
    return self.fs.exists(path) and self.fs.isfile(path)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/fsspec/asyn.py", line 121, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/s3fs/core.py", line 566, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/mallinger/tmp/s3fs-test/lib/python3.8/site-packages/s3fs/core.py", line 740, in _info
    if out["KeyCount"] > 0:
KeyError: 'KeyCount'
```

**What you expected to happen**:
The example should print True or False.

**Minimal Complete Verifiable Example**:

```python
import s3fs
s3 = s3fs.S3FileSystem(
    client_kwargs={"endpoint_url": "https://obs.eu-de.otc.t-systems.com"}
)
store = s3fs.S3Map("s3://REDACTED/REDACTED", s3=s3)
print('a' in store)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: I reproduced this in a virtualenv with only `s3fs` installed
- Python version: 3.9 and 3.8
- Operating System: python docker container and also Ubuntu LTS
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Yes, it is supposed to be there: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2

However, it could be generalised as follows:
```
if out.get("KeyCount", 0) > 0 or out.get("Contents", []) or out.get("CommonPrefixes", []):
```

Please try is this works for you, and submit a PR to make a change if so. Unfortunately, we won't be able to test this exact case.

**Comment by totycro** [comment]
Awesome! This works because if the file is present, i get the `"Contents"` key.

The API response with this keys if the file is *not* present:
`['ResponseMetadata', 'IsTruncated', 'Name', 'Prefix', 'Delimiter', 'MaxKeys']`
And with these keys if the file *is* present:
`['ResponseMetadata', 'IsTruncated', 'Contents', 'Name', 'Prefix', 'Delimiter', 'MaxKeys']`
