### ISSUE TITLE
fs.glob doesn't work as expected

### ISSUE THREAD

**Issue by oeway** [dask/s3fs#415]
**What happened**:
`fs.glob` failed to list the files when using `*` to match file extensions:
```python
>>> fs = s3fs.S3FileSystem(key='mykey', secret='mysecret', client_kwargs={"endpoint_url": 'myendpoint', "region_name": "EU"},)
>>> fs.touch('/my-bucket/folder/myfile.json')
>>> fs.exists('/my-bucket/folder/myfile.json')
True
>>> fs.glob('/my-bucket/folder/myfile.*')
[]
```
**What you expected to happen**:
```python
>>> fs.glob('/my-bucket/folder/myfile.*')
['/my-bucket/folder/myfile.json']
```

**Environment**:
- s3fs version: '0.5.2'
- Python version: 3.7
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I'm sorry, I am not seeing this - would you mind testing with fsspec and s3fs at master?

**Comment by oeway** [comment]
Hi @martindurant Thanks for your response. I just tested with the fsspec and s3fs at master, however, I get the same result.

```python
>>> s3fs.__version__
'0.5.2+16.g2c1e526'
>>> fsspec.__version__
'0.8.5+58.gc2b6eab'
```

**Comment by martindurant** [comment]
I believe this is now fixed
