### ISSUE TITLE
Method create_client() is failing

### ISSUE THREAD

**Issue by jcunhafonte** [dask/s3fs#418]
**What happened**:

s3 = S3FileSystem(client_kwargs={'aws_access_key_id': 'foo', 'aws_secret_access_key': 'bar'})
>  TypeError: create_client() got multiple values for keyword argument 'aws_access_key_id'

**What you expected to happen**:
This should be working as 0.5.1

**Environment**:

- s3fs version: 0.5.2
- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Because those args are among the most commonly seen, they are handled at the top level:
```python
s3 = S3FileSystem(key='foo', secret='bar')
```
