### ISSUE TITLE
Read invalid file content, due to file-size "caching"

### ISSUE THREAD

**Issue by anetbnd** [dask/s3fs#422]
Bug reports that follow these guidelines are easier to diagnose, and so are often handled much more quickly.
-->

**What happened**:
If a `S3File` object is read, it can happen that invalid content is read, due to internal file-size caching in the variable `S3File.size`, if between opening the file and reading it the file in the S3 has changed. This happens, because the file size if stored into the object variable when opening the file, while the actual reading from the file happens only when the `read()` method of the `S3File` object is called. If the "all" cache-type is used for this file, this triggers a `get_object` request on S3 with a range attribute of `0-self.size`.

Example (see code below):
1.) The file is written with 3 bytes to the bucket.
2.) We can read the file without issues.
3.) Then we open the file again (size is setup with value 3)
4.) But now we change the content to have more bytes
5.) When reading now, we just read 3 bytes instead the full content

**What you expected to happen**:

It is clear, that s3fs cannot handle those race-conditions well. There will always be some kind of caching which could lead to invalid behavior when other processes change data in the background. However, at the moment s3fs just silently delivers any content and if the higher layer application cannot check if the content makes sense, it could happen that the read error is not noticed and lead to many other errors in the application. 

My expectation would be that in those cases s3fs notifies the caller with a clear exception, which states that the file has been changed after opening it, thus is cannot be read anymore in a safe manner. This can easily achieved by adding the `IfMatch` attribute to the `get_object` call of boto3 and use here the last read ETag, which is already stored in the directory `S3File.details`. In this case boto3 would generate an exception, telling the user that the file has changed. 

The simplest solution would be to add it in the `__init__` method of `S3File`:

```
        # ....

        if 'r' in mode:
            self.req_kw['IfMatch'] = self.details['ETag']
``` 

Then the application of the user can catch this exception and decide what to do. For example read the file another time.
To make it specially clean, it would also be possible to translate the exception from a boto3 exception into a exception, which tells the user, that the file has changed between opening and reading. 

**Minimal Complete Verifiable Example**:

In this example, I simulate the concurrent write with a direct boto3 call, to not accidentally change an inner state of the s3fs object (any caches or something like that). 

```python
import s3fs
import boto3
import botocore.config


PROXY = None
AWS_KEY = '...'
AWS_SECRET = '...'
USE_SSL = False
BUCKET = '...'
FILE = 'test.file'
FILE_PATH = f's3://{BUCKET}/{FILE}'

def create_file(boto_client, content: bytes):
    object = boto_client.Object(BUCKET, FILE)
    object.put(Body=content)


fs = s3fs.S3FileSystem(
    anon=False,
    key=AWS_KEY,
    secret=AWS_SECRET,
    config_kwargs={'proxies':{'http': PROXY, 'https': PROXY}},
    use_ssl=USE_SSL,
)

boto_session = boto3.session.Session(
    aws_access_key_id=AWS_KEY,
    aws_secret_access_key=AWS_SECRET,
)

boto_client = boto_session.resource(
    's3',
    use_ssl=USE_SSL,
    config=botocore.config.Config(proxies={'http': PROXY, 'https': PROXY})
)


create_file(boto_client, b'123')

with fs.open(FILE_PATH, 'rb') as f:
    content = f.read()
    assert content == b'123', f"content was {content}"

with fs.open(FILE_PATH, 'rb') as f:
    create_file(boto_client, b'ABCDEFGHIJKLMN')

    content = f.read()
    assert content == b'ABCDEFGHIJKLMN', f"content was {content}"
```

**Anything else we need to know?**:

This error happens seldom, but in combination with another error (I will create another bug report), this error can happen very often, also without race condition.

**Environment**:

- Dask version: not installed
- Python version: 3.8.5
- Operating System: windows 10, ubuntu 16.04
- Install method (conda, pip, source): conda and pip

**pip list**:
```
aiobotocore              1.1.2
aiohttp                  3.6.2
aioitertools             0.7.0
aniso8601                7.0.0
appdirs                  1.4.4
argon2-cffi              20.1.0
async-generator          1.10
async-timeout            3.0.1
atomicwrites             1.4.0
attrs                    20.3.0
backcall                 0.2.0
bleach                   3.2.1
boto3                    1.14.44
botocore                 1.17.44
cachetools               4.1.1
certifi                  2020.12.5
cffi                     1.14.3
chardet                  3.0.4
click                    7.1.2
colorama                 0.4.4
coverage                 5.3
cryptography             3.1.1
decorator                4.4.2
defusedxml               0.6.0
distlib                  0.3.1
dlc                      1.2.8
docutils                 0.15.2
easydict                 1.9
entrypoints              0.3
et-xmlfile               1.0.1
filelock                 3.0.12
flake8                   3.8.4
Flask                    1.1.2
Flask-Caching            1.9.0
Flask-Cors               3.0.9
Flask-GraphQL            2.0.1
Flask-Login              0.5.0
fsspec                   0.8.5
gitdb                    4.0.5
GitPython                3.1.12
google-auth              1.22.1
graphene                 2.1.8
graphql-core             2.3.2
graphql-relay            2.0.1
graphql-server-core      1.2.0
idna                     2.10
importlib-metadata       2.0.0
iniconfig                1.0.1
ipykernel                5.3.4
ipython                  7.19.0
ipython-genutils         0.2.0
ipywidgets               7.5.1
itsdangerous             1.1.0
jdcal                    1.4.1
jedi                     0.17.2
Jinja2                   2.11.2
jmespath                 0.10.0
jsonschema               3.2.0
jupyter                  1.0.0
jupyter-client           6.1.7
jupyter-console          6.2.0
jupyter-core             4.7.0
jupyterlab-pygments      0.1.2
kubernetes               11.0.0
MarkupSafe               1.1.1
mccabe                   0.6.1
mistune                  0.8.4
multidict                4.7.6
mypy                     0.790
mypy-extensions          0.4.3
nbclient                 0.5.1
nbconvert                6.0.7
nbformat                 5.0.8
nest-asyncio             1.4.3
notebook                 6.1.4
numpy                    1.19.2
oauthlib                 3.1.0
openpyxl                 3.0.5
openshift                0.11.2
packaging                20.4
pandas                   1.1.2
pandocfilters            1.4.3
parso                    0.7.0
pickleshare              0.7.5
pip                      20.3.3
pluggy                   0.13.1
prometheus-client        0.8.0
promise                  2.3
prompt-toolkit           3.0.8
py                       1.9.0
pyarrow                  3.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.6.0
pycparser                2.20
pyflakes                 2.2.0
Pygments                 2.7.2
PyJWT                    2.0.1
pyparsing                2.4.7
pyrsistent               0.17.3
pytest                   6.1.2
pytest-cov               2.10.1
pytest-pythonpath        0.7.3
python-dateutil          2.8.1
python-string-utils      1.0.0
pytz                     2020.1
pywin32                  227
pywinpty                 0.5.7
PyYAML                   5.3.1
pyzmq                    19.0.2
qtconsole                4.7.7
QtPy                     1.9.0
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
ruamel.yaml              0.16.12
ruamel.yaml.clib         0.2.2
Rx                       1.6.1
s3fs                     0.5.1
s3transfer               0.3.3
Send2Trash               1.5.0
setuptools               49.6.0.post20200814
setuptools-scm           4.1.2
sip                      4.19.13
six                      1.15.0
smmap                    3.0.4
terminado                0.9.1
testpath                 0.4.4
toml                     0.10.1
tornado                  6.0.4
tox                      3.21.0
tox-setuptools           1.3.3
traitlets                5.0.5
typed-ast                1.4.1
typeguard                2.10.0
typing-extensions        3.7.4.3
urllib3                  1.25.10
virtualenv               20.3.0
wcwidth                  0.2.5
webencodings             0.5.1
websocket-client         0.57.0
Werkzeug                 1.0.1
wheel                    0.35.1
widgetsnbextension       3.5.1
wincertstore             0.2
wrapt                    1.12.1
yarl                     1.6.0
zipp                     3.4.0
```

**Comment by martindurant** [comment]
Your assessment sounds correct, and the solution reasonable. Would you like to implement this? The code you provide would essentially become a test case.

**Comment by anetbnd** [comment]
@martindurant I cannot promise it, because I first need to check if I can run on my windows computer the test suite to ensure I don't break anything. Tomorrow I can give feedback about this.

**Comment by martindurant** [comment]
That's totally fine, I appreciate you having a go.

**Comment by anetbnd** [comment]
@martindurant One further question: In case I implement the code change: What do you think about translating the generic boto3 exception to a more meaningful exception (the boto3 exception, just says that a precondition failed, but does not explain why, because this only comes from the context). Which name you want to have for this exception and in which file to store it?

**Comment by martindurant** [comment]
It would fit into s3fs.utils, and I would call it FileExpired(IOError)("The remote file corresponding to filename %s and Etag %s no longer exists"). There's probably a better name.

**Comment by anetbnd** [comment]
@martindurant That's a good name and text! I check tomorrow, if I can setup the tests and if so, I will prepare a pull-request.
Thanks for your assistance!
