### ISSUE TITLE
add s3fs.S3FileSystem(profile=PROFILE) to docs

### ISSUE THREAD

**Issue by raybellwaves** [dask/s3fs#426]
Came across this today: https://github.com/dask/s3fs/issues/324#issuecomment-683131626

It may be worth mentioning in
https://s3fs.readthedocs.io/en/latest/index.html#credentials

**Comment by martindurant** [comment]
Sounds reasonable. I wonder if the docs of the various backends should, after all, be more centralised around fsspec...

**Comment by raybellwaves** [comment]
Am I right in thinking that if you have an environmental variable called `AWS_PROFILE` setting anom=False will default to that profile

**Comment by martindurant** [comment]
Yes I believe so - s3fs will just let botocore pick auth as it sees fit, and that is one of the [variables that are consulted](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables).
