### ISSUE TITLE
Exception translation logic creates recursion in some cases

### ISSUE THREAD

**Issue by isidentical** [dask/s3fs#442]
`raise translate_boto_error(captured_error) from captured_error` is a common pattern in the codebase, though the problem with this is that `translate_boto_error` might return the same exception and it would create a recursion of `__cause__` since `x_exception.__cause__` is itself (`is x_exception`) which would prevent anyone from traversing it easily;
https://github.com/dask/s3fs/blob/1333a8d46d38fd8d4c85536972cafcba998fd62e/s3fs/core.py#L253

This pattern can be replaced via 
```py
new_exc = translate_boto_error(exc)
if new_exc is exc:
     raise exc
else:
    raise new_exc from exc
```
but since it would create a lot of code duplication, I think a better way would be directly using `raise translate_boto_error(exc)` directly and setting the `__cause__` there to the new exception so that we can avoid the recursion and also the code duplication at the same time.

**Comment by isidentical** [comment]
@martindurant would you mind publish a new release that includes both patches?

**Comment by martindurant** [comment]
Yes, it is on my list.

**Comment by isidentical** [comment]
Thanks!
