### ISSUE TITLE
py3.6 >= support

### ISSUE THREAD

**Issue by isidentical** [dask/s3fs#445]
I see that 3.6 support dropped in [this](https://github.com/dask/s3fs/commit/61ba003750cbb57db44257c4aa1cfa8d6ce326fd) commit though it is not clear about reasoning. I would assume it is because it's EOL coming in 9 months, though 3.6 might still be one of the most used versions. Would it make sense to bring the support back?

**Comment by martindurant** [comment]
The happened after the confluence of a couple of things
- a general move in the pydata ecosystem (like pandas, dask and many more)
- a specific async issue in fsspec that I could not resolve for py 3.6

The latter point *might* have been avoided in https://github.com/intake/filesystem_spec/pull/572 , but I'd like to avoid possible differences in asyncio API for py36.

> 3.6 might still be one of the most used versions

This maybe true, but those on py36 probably don't install the latest releases of packages like s3fs.

**Comment by isidentical** [comment]
> a general move in the pydata ecosystem (like pandas, dask and many more)

When would you think that filesystem-spec wil drop the 3.6 support though?

**Comment by martindurant** [comment]
That is up for debate. If we are to have it, then the CI should be made to run on 3.6. I don't know if the async thing will work or not. Most implementations don't need it, but HTTP, abfs, s3fs and gcsfs **do**.

**Comment by isidentical** [comment]
> That is up for debate. If we are to have it, then the CI should be made to run on 3.6. I don't know if the async thing will work or not. Most implementations don't need it, but HTTP, abfs, s3fs and gcsfs do.

I can try to send a pull request that adds workflows, though I guess we should move the discussion over there?

**Comment by martindurant** [comment]
Sounds good
