### ISSUE TITLE
Implement S3FileSystem.set_session

### ISSUE THREAD

**Issue by andreasg123** [dask/s3fs#454]
For consistency with other `fspec` async implementations, could you implement `S3FileSystem.set_session`, returning an object with an async `close` method?
https://filesystem-spec.readthedocs.io/en/latest/async.html#using-from-async

Currently, `_connect` performs the function of `set_session`. However, its return value and the need to call `await close()` on it isn't documented.
https://s3fs.readthedocs.io/en/latest/#async

**Comment by martindurant** [comment]
That is a reasonable ask. This particular implementation is very new, having gone around a few circles, but what you propose makes sense. Did you have a way to do this in mind already? I'd be happy to see a PR.

**Comment by andreasg123** [comment]
I think `_connect` could just be renamed to `set_session`. Then, it would only need a little more documentation.

**Comment by martindurant** [comment]
I don't immediately have the time to look, but you are probably right.

**Comment by martindurant** [comment]
You could make the change and add an alias so that any code using the previous name (`_connect`) will still work. Later we can deprecate it.
