### ISSUE TITLE
new release of `fsspec==0.9.0` breaks `s3fs` on import

### ISSUE THREAD

**Issue by r-luo** [dask/s3fs#455]
**What happened**:

```python
import s3fs
```
raises the following error
```python
ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (/databricks/python/lib/python3.7/site-packages/fsspec/asyn.py)
```

**What you expected to happen**:

import shouldn't have failed

**Minimal Complete Verifiable Example**:

```bash
pip install s3fs
pip install fsspec==0.9.0
python
>>> import s3fs
```

**Anything else we need to know?**:
pinning `fsspec` to `0.8.7` resolves the issue

**Environment**:

- Dask version: -
- Python version: 3.8
- Operating System: Mac OS X
- Install method (conda, pip, source): pip

**Comment by r-luo** [comment]
`fsspec` literally just made the release an hour ago and it broke s3fs on DataBricks as DataBricks automatically installs the newest version of all packages...

Recommend pinning `fsspec` in the requirement for `s3fs` before adapting to the new `fsspec` version

**Comment by martindurant** [comment]
duplicate of https://github.com/intake/filesystem_spec/issues/597

**Comment by martindurant** [comment]
(sorry, didn't mean to close, but will release s3fs right away. pypi has been buggy today)
