### ISSUE TITLE
Incompatible with fsspec 0.9.0

### ISSUE THREAD

**Issue by shughes-uk** [dask/s3fs#457]
Installing s3fs, if  fsspec 0.9.0 is installed you end up with 

```
/opt/conda/lib/python3.8/site-packages/fsspec/registry.py:211: in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
/opt/conda/lib/python3.8/site-packages/fsspec/registry.py:226: in _import_class
    mod = importlib.import_module(mod)
/opt/conda/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
/opt/conda/lib/python3.8/site-packages/s3fs/__init__.py:1: in <module>
    from .core import S3FileSystem, S3File
/opt/conda/lib/python3.8/site-packages/s3fs/core.py:11: in <module>
    from fsspec.asyn import AsyncFileSystem, sync, sync_wrapper, maybe_sync
E   ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py)
```

This tricks fsspec into thinking s3fs is not installed as a side effect.

I assume upgrading to s3fs 0.6.0 solves this.

**Comment by RafaelFigueiredo** [comment]
I have several automations that use s3fs, I could solve for some of them updating the s3fs==0.6.0 but the error keeps happening in others. the final solution was to fix my requirements.txt fsspec==0.8.7

**Comment by eric-svg** [comment]
> I have several automations that use s3fs, I could solve for some of them updating the s3fs==0.6.0 but the error keeps happening in others. the final solution was to fix my in requirements.txt `fsspec==0.8.7` and `s3fs==0.5.2`

Was this using python 3.9?  Having similar issues.  Just pulled in s3fs 0.6.0 and still getting the import maybe_sync error.

**Comment by martindurant** [comment]
If I do
```
$ conda create -n tester python=3.9 fsspec s3fs ipython
$ conda activate tester
$ ipython
[1] import s3fs
```
No problem. This gets fsspec 0.9.0, s3fs 0.6.0.

Similarly
```
$ conda create -n tester python=3.9
$ conda activate tester
$ pip install s3fs
$ python
>>> import s3fs
>>> s3fs.__version__
'0.6.0'
```

**Comment by shughes-uk** [comment]
This issue was popping up when when fsspec 0.9.0 was on conda-forge but s3fs 0.6.0 had not quite made it. Might still be an idea to update the reqs to prevent bad solves.

**Comment by martindurant** [comment]
OK, got it - thanks for the info.
I'll try to come up with a foolproof release pattern for the set of packages for the future.
