### ISSUE TITLE
order versions appear broken due to recent fsspec changes

### ISSUE THREAD

**Issue by vasili-zolotov** [dask/s3fs#465]
@martindurant I see that `fsspec.asyn` module got rid of `maybe_sync` function, but older versions of `s3fs` still rely on the method which now fails to import. For example `s3fs==0.5.2` now does not seem to work after a clean install. I see that s3fs requirements.txt asked for `fsspec>=0.8.0` and that is now incompatible without an upper boundary.

**Comment by martindurant** [comment]
Yes, you are right.
This is not unusual! If you know you need an older version of s3fs, then you will have to analyse your full set of packages to find compatible versions.

For reference, I mean in the future to do two things:
- move to calendar versioning, since the "semantics" of x.y.z are often confusing for a dev-facing library like this
- always release fsspec, s3fs and gcsfs together
- explicitly pin s3fs and gcsfs's version to the co-released fsspec. That means more work for me.

**Comment by vasili-zolotov** [comment]
Thanks for responding. As another option I could also see reserving y in x.y.z for breaking changes and specifying upper bound always in a proactive way. If I have to choose between always using the bleeding edge dependency and using one that definitely works I'd always choose the latter. In any case, thanks again for keeping it alive and improving!

**Comment by martindurant** [comment]
"breaking changes" are too hard to identify for libraries so closely tied

**Comment by jmcgrath207** [comment]
Had a similar issue where fspec 0.9.0 and above don't work when I use `s3fs.S3FileSystem(asynchronous=True` however when I downgrade to version 0.8.7 my code is working again. It appears they removed the `maybe_sync` method.

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/john/PycharmProjects/da_data_pipeline/normalized-redis-lambda/sam/service_logic/__init__.py", line 18, in <module>
    import s3fs
  File "..................../s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "..................../s3fs/core.py", line 12, in <module>
    from fsspec.asyn import AsyncFileSystem, sync, sync_wrapper, maybe_sync
ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn' (..................../fsspec/asyn.py)

Process finished with exit code 1

```

**Comment by psdon** [comment]
I encounter another error related to `fsspec` when I run `pytest`
```
scrapy_project/project/utils.py:9: in <module>
    import s3fs
../../.conda/envs/d-scraper/lib/python3.8/site-packages/s3fs/__init__.py:1: in <module>
    from .core import S3FileSystem, S3File
../../.conda/envs/d-scraper/lib/python3.8/site-packages/s3fs/core.py:11: in <module>
    from fsspec.utils import infer_storage_options, tokenize, setup_logging
E   ImportError: cannot import name 'setup_logging' from 'fsspec.utils' (/home/me/.local/lib/python3.8/site-packages/fsspec/utils.py)
================================================================== short test summary info ===================================================================
ERROR  - ImportError: cannot import name 'setup_logging' from 'fsspec.utils' (/home/me/.local/lib/python3.8/site-packages/fsspec/utils.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================== 1 error in 1.00s ======================================================================

```

**Comment by martindurant** [comment]
@psdon - the function is [there](https://github.com/intake/filesystem_spec/blob/0.9.0/fsspec/utils.py#L425) in the 0.9.0 fsspec code. Please see the discussion above and update your version of fsspec.
