### ISSUE TITLE
Export FileExpired for use by consumers

### ISSUE THREAD

**Issue by jeffplourde** [dask/s3fs#479]
`FileExpired` is an elegant solution https://github.com/dask/s3fs/pull/428.

My problem is that it's not exported from the module so I can't catch it. Instead I'm catching its parent `IOError`. Am I missing something about how to import it? Was it only intended for internal use? Apologies if it's obvious to everyone but me.

**Comment by anetbnd** [comment]
Hello @jeffplourde 

Sorry for the late answer.
You can use it from the `s3fs.utils` namespace like that:

```python
from s3fs.utils import FileExpired
```

**Comment by jeffplourde** [comment]
Thank you @anetbnd. I suspect my virtual environment was in a questionable state when importing failed for me previously. My apologies for the non-issue issue. Thanks for your patience.
