### ISSUE TITLE
s3fs: supporting find() on arbitrary prefixes (like glob('a/b/prefix*')) with better performance

### ISSUE THREAD

**Issue by isidentical** [dask/s3fs#485]
When listing only files that start with a certain prefix `foo/bar/b*` `glob()` is handy though in terms of s3 (and also other clouds) it is not as performant as just doing this on the server-side with not adding the final `/` suffix. Especially when the parent directories size is greater than a single listing call (1024). Here is an example;

```py
import time
import secrets
from s3fs import S3FileSystem
from pprint import pprint
from concurrent.futures import ThreadPoolExecutor, as_completed

bucket = 'temp/cache/00/'

def worker(fs, bucket, prefix=''):
    fs.touch(bucket + prefix + secrets.token_hex())

def make_files():
    fs = S3FileSystem()
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = [
            executor.submit(worker, fs, bucket)
            for _ in range(9900)
        ]
        futures += [
            executor.submit(worker, fs, bucket, '0')
            for _ in range(100)
        ]
        
        for n, future in enumerate(as_completed(futures), 1):
            future.result()
            print(f'{n}/10000 completed')
```

it creates 10_000 files where 100 of them are guaranteed to start with `0` prefix and 9900 random files that can start with anything. In the following case if I do a `glob('temp/cache/00/0*')` it takes about 22 seconds compared to a single find call with a new option (`use_prefix: bool = True`) it takes about 3~ seconds `find('temp/cache/00/0', use_prefix=True)`.

**Comment by martindurant** [comment]
Agreed that use_prefix can be useful for any of the listings methods, as you show. We already have the logic to make this work, I thought?
It does come at the disadvantage that these partial listings would not be cached, so you could end up spending more time in some cases.

**Comment by isidentical** [comment]
> We already have the logic to make this work, I thought?

I don't think there is any options to do so, at least not within the public api. 

> It does come at the disadvantage that these partial listings would not be cached, so you could end up spending more time in some cases.

At least in our case, we don't use the dircache that much so it won't be affecting us. And since this is going to be a new option, there won't be any regressions either.

**Comment by isidentical** [comment]
So apparently adlfs already does this, but the behaviour and the options differ from the implementation that I proposed.  I think it might be better to follow it. 

https://github.com/dask/adlfs/blob/96958331854c5a67917d4c9a802a62720d091374/adlfs/spec.py#L901-L918

So what they do is that, for searching for `a/b/c/test_*` you do `fs.find('a/b/c/', prefix='test_'). The default prefix is `""` so if you don't specify it, it will just list everything under it. However, the major difference is that, if there is a file that has the same exact name with the prefix under the original path (in this case if there is a file named `/a/b/c/test_`, it won't be returned) , then it won't be yielded. I don't know much about the reasoning though it would've been more compliant if it were to return those. In any case, I believe that if we are going to adopt this methodology, it is better for downstream clients to offer a unified API for major object based storages that support the same optimization (s3fs, gcsfs, adlfs). 

What do you think @martindurant?

**Comment by martindurant** [comment]
Yes, I totally agree that uniformity is very important here, we should strive for it. I think I like how they have names things better. It would be worth checking what happens if `prefix` contains a "/": should be an exception?

As for whether the exact match is returned, I think I agree that it should - it may be that the current behaviour in adlfs is not intentional.

Obviously we'll have to port whatever we do here to gcsfs too.

**Comment by isidentical** [comment]
> It would be worth checking what happens if prefix contains a "/": should be an exception?

I'd say we should leave it as an implementation detail (to the cloud provider).

> As for whether the exact match is returned, I think I agree that it should - it may be that the current behaviour in adlfs is not intentional.

Agreed.

> Obviously we'll have to port whatever we do here to gcsfs too.

Indeed, that is on my plans. Will adjust the existing s3fs PR to reflect that.

**Comment by isidentical** [comment]
> Obviously we'll have to port whatever we do here to gcsfs too.

@martindurant gcsfs already supports this as is, but it doesn't have tests / docs. I don't know how to generate the casettes though if you'd like to add these, I guess it makes sense to just copy the stuff here and replace s3 with gs. I can also do that if you volunteer for VCR generation.
