### ISSUE TITLE
Abbility to update cached data without deleting whole cache

### ISSUE THREAD

**Issue by zeljkostojkovic** [dask/s3fs#490]
**Problem:** I have created AWS Lambda function for preprocessing data. The lambda is triggered every time new file arrives in a S3 bucket, preprocess data and writes data into a new file on another S3 bucket. The problem occurs when two files arrive in the S3 bucket at an interval of ~ 30 seconds. Since the `s3 = s3fs.S3FileSystem(anon=False)` is initialized when lambda is triggered for the first file, it lists all files inside that S3 bucket and put that information inside cache, so when second file arrives, it throws `FileNotFoundError` error since the second file is not listed in the cache. This problem does not occur when files arrive at an interval of more than 5 minutes, because in that period the instance of the first Lambda function ends, so a new instance is initialized for the second file.

Also, the `s3.invalidate_cache()` does not resolve problem, because it erases the entire cache, which also contains the credentials for accessing the S3 bucket and after that it throws `PermissionError: Access Denied Traceback` error.

**Current Solution:** I was forced to call the `s3.ls(refresh=True)` command within the lambda function (with the `refresh` argument set to `True`), because I noticed in the source code that the cache is updated as part of this function.

**New Feature:** Creating a function that would be able to update cache or some part of the cache passed through the arguments of the function, so that we would not be forced to use functions we don't really need inside our code, just to change the state of the cache

**Comment by martindurant** [comment]
> Also, the s3.invalidate_cache() does not resolve problem, because it erases the entire cache, which also contains the credentials for accessing the S3 bucket 

This should definitely not happen! I would say that you were doing the right thing, and any loss of credentials is due to something else that should be investigated.

> Creating a function that would be able to update cache or some part of the cache passed through the arguments of the function, so that we would not be forced to use functions we don't really need inside our code, just to change the state of the cache

The listings cache is a fiddly thing. I'm not sure how your proposal would look exactly, but you should be aware that you can turn off directory caching altogether with `use_listings_cache=False` or set a time-to-live with `listings_expiry_time=`.
