### ISSUE TITLE
__init__ error with S3FileSystem().glob

### ISSUE THREAD

**Issue by upjohnc** [dask/s3fs#505]
**What happened**:
Running `S3FileSystem().glob` raises an exception:
`TypeError: __init__() got an unexpected keyword argument 'verify_ssl'`

traceback:
```
~/.virtualenvs/peach-2-qyx6eVvu/lib/python3.7/site-packages/aiobotocore/endpoint.py in create_endpoint(self, service_model, region_name, endpoint_url, verify, response_parser_factory, timeout, max_pool_connections, http_session_cls, proxies, socket_options, client_cert, proxies_config, connector_args)
347             verify_ssl=bool(verify),
348             ssl=ssl_context,
--> 349             **connector_args)
350
351         aio_session = http_session_cls(

TypeError: __init__() got an unexpected keyword argument 'verify_ssl'
```

**Minimal Complete Verifiable Example**:

```python
In [1]: from s3fs import S3FileSystem

In [2]: t = S3FileSystem()

In [4]: t.glob(f"s3://<bucket>/DRG/data/raven/incremental_extract/*/manifest/manifest.done")
```

**Anything else we need to know?**:
under s3fs version 2021.06.0, the glob function in our code base

**Environment**:

- Dask version: 2021.07.0
- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
The first thing I would do it to check that your aiobotocore and botocore versions are exactly compatible - they should be tightly pinned. https://github.com/aio-libs/aiobotocore/releases

**Comment by upjohnc** [comment]
That is a fair question.  It seems that the setup is "ok" based on the requirements defined in the packages.

In reviewing the dependency tree, this is what I have:

- s3fs 2021.7.0:
    - aiobotocore [required: >=1.0.1, installed: 1.3.3]
    - botocore [required: >=1.20.106,<1.20.107, installed: 1.20.106]
- boto3 1.17.49:
    - botocore [required: >=1.20.49,<1.21.0, installed: 1.20.106]
- aiobotocore 1.3.3:
    - botocore>=1.20.106,<1.20.107, installed: 1.20.106

Based on this dependency tree, do you have a recommendation of which maintainer to contact - meaning I am assuming that the problem is that one of the "boto"s isn't playng well with the others?

**Comment by martindurant** [comment]
It would be worth checking if a new environment with s3fs/botocore/aiobotocore (i.e., no boto3) also shows the problem.

**Comment by upjohnc** [comment]
I did a `pip uninstall boto3` and now have this in my virtualenv.
```
➜ pip list | rg boto
aiobotocore                       1.3.3
botocore                          1.20.106
botocore-stubs                    1.21.6
```

The same exception is raised.

**Comment by martindurant** [comment]
https://github.com/vaexio/vaex/issues/1053 suggests aiohttp may be the culprit

**Comment by upjohnc** [comment]
a pre-release version of aiohttp is in the virtual env.  `4.0.0a1`.  I changed the version to `<4.0.0` and than seemed to work.

We use pipenv so I will need to see why pipenv allowed this pre-release through.
