### ISSUE TITLE
aiobotocore 1.4.0  has no attribute AioSession

### ISSUE THREAD

**Issue by joshmoore** [dask/s3fs#513]
**What happened**:

Zarr tests with aiobotocore 1.4.0 (released 4 hours ago) fails with:

```
        conf = AioConfig(**config_kwargs)
>       self.session = aiobotocore.AioSession(**self.kwargs)
E       AttributeError: module 'aiobotocore' has no attribute 'AioSession'

/usr/share/miniconda/envs/zarr-env/lib/python3.8/site-packages/s3fs/core.py:364: AttributeError
```

see: https://github.com/zarr-developers/zarr-python/pull/812/commits/9c56c8b23117f88aeb57533f00180c4cb45e8f59

**What you expected to happen**:

Pinning to earlier versions works fine.

**Comment by jrbourbeau** [comment]
Thanks for reporting @joshmoore! This should be closed by https://github.com/dask/s3fs/pull/510

**Comment by joshmoore** [comment]
🤦🏽  I looked for issues but not for _PRs_. Just too fast. :heart:
