### ISSUE TITLE
Incompatible with aiobotocore==1.4.0

### ISSUE THREAD

**Issue by f4hy** [dask/s3fs#514]
**What happened**:
After upgrading to aiobotocore we get an error `module 'aiobotocore' has no attribute 'AioSession'`

**What you expected to happen**:
dependencies should exclude 1.4.0 until it is made compatible.

**Comment by r-luo** [comment]
https://github.com/dask/dask/issues/8070

**Comment by martindurant** [comment]
A fix was merged and released to pypi: 2021.08.0 . Release on conda-forge will first require https://github.com/conda-forge/aiobotocore-feedstock/pull/39

**Comment by andrewfogg** [comment]
@f4hy I think I am encountering a related issue https://stackoverflow.com/questions/68864939/s3fs-suddenly-stopped-working-in-google-colab-with-error-attributeerror-module

**Comment by f4hy** [comment]
This has been resolved with the latest release. Thanks all!
