### ISSUE TITLE
Using put to overwrite an existing remote directory with a local directory results in the local and remote paths being switched

### ISSUE THREAD

**Issue by justinl2s** [dask/s3fs#518]
**What happened**:

When overwriting an existing remote directory, rpath, with the contents of a local directory, lpath, the **put(lpath, rpath[, recursive, callback])** method appears to replace the rpath with the lpath and results in an exception as it tries to write to the bucket "home" which I do not have access to" (home happens to be the first component of the local path)

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied. User (justinl2s) does not have access right to perform OBJECT_WRITE to bucket (home).

**What you expected to happen**:

The contents of the local directory, lpath, should overwrite the contents of the remote directory, rpath,

Calling 
**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
# Assume I have a local directory "/home/justinl2s/cool-directory" with 2 files "file1.txt" and "file2.txt" 
# as well as a S3 bucket created at S3://justin-test that I own

import s3fs

fs = s3fs..S3FileSystem()

fs.put("/home/justinl2s/cool-directory", "s3://justin-test/cool-directory", recursive=True)

# this exception is returned
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied. User (justinl2s) does not have access right to perform OBJECT_WRITE to bucket (home).
```

**Anything else we need to know?**:

**Environment**:

- s3fs version: 0.4.2
- Dask version: 
- Python version: 3.7
- Operating System: Debian GNU/Linux 9 (stretch)
- Install method (conda, pip, source):

**Comment by martindurant** [comment]
Your example looks very similar to this test, which currently performs as expected
```python
def test_upload_recursive_to_bucket(s3, tmpdir):
    # GH#491
    folders = [os.path.join(tmpdir, d) for d in ["outer", "outer/inner"]]
    files = [os.path.join(tmpdir, f) for f in ["outer/afile", "outer/inner/bfile"]]
    for d in folders:
        os.mkdir(d)
    for f in files:
        open(f, "w").write("hello")
    s3.put(folders[0], "newbucket", recursive=True)
```
(Note link to #491 )

Can you spot what is different with your workflow? Changing the target to "s3://newbucket" does not cause a problem.

**Comment by martindurant** [comment]
Also note, that if I run the `put` line *twice* (i.e., overwriting the first copies), it also succeeds.

**Comment by justinl2s** [comment]
After stepping through the code in pdb, I've identified the lines where this is happening. It's in [filesystem_spec (v0.7. 2)
](https://github.com/intake/filesystem_spec/blob/0.7.2/fsspec/spec.py)
At [L628](https://github.com/intake/filesystem_spec/blob/0.7.2/fsspec/spec.py#L628), a value is calculated for the variable `rootdir` that's made up of `lpath` (/home/justinl2s/cool-directory) and the directory I run the script from. (ex. `rootdir = /home/justinl2s/path/to/my/script/cool-directory`)

`rpath` (`s3://justin-test`) exists so we step into [L633](https://github.com/intake/filesystem_spec/blob/0.7.2/fsspec/spec.py#L633). This creates a new variable `rpath2` and assigns it a value that ends up just being equal to `rootdir`

`rpath2` is used as a prefix to create file paths in the `rpaths` list in [L638 ](https://github.com/intake/filesystem_spec/blob/0.7.2/fsspec/spec.py#L638)which is ultimately used to do the remote write at [L651](https://github.com/intake/filesystem_spec/blob/0.7.2/fsspec/spec.py#L651). Since the paths in the `rpaths` list are all prefixed by `rpath2` which is essentially `rootdir`, it ends up trying to write to the bucket `home` 

Do you know if this is by-design? (Perhaps it's a question to ask on the filesystem_spec project) Later versions of the `spec.py` file in filesystem_spec don't seem to do this

**Comment by martindurant** [comment]
> Later versions of the spec.py file in filesystem_spec don't seem to do this

You mean this got fixed? Then I suppose it was just a bug.

**Comment by justinl2s** [comment]
Yes, the issue is no longer reproducible if I use fsspec_2021_6_1.
