### ISSUE TITLE
Meaningful versioning

### ISSUE THREAD

**Issue by docktermj** [dask/s3fs#529]
I appreciate that you are versioning according to year-month-day (YYYY-MM-DD),   However it doesn't tell me anything important about importing a version of the `s3fs` into a python program.  For instance 0.4.2 worked, but 2021.08.01 broke do to dependency conflicts.  (Ref: https://github.com/dask/s3fs/issues/528)  

The question is:  When did the backward breaking change occur?

Many folks use Semantic Versioning (https://semver.org/) to communicate breakage, new features, and patches.

I hope you'll consider Semantic Versioning in the future.

**Comment by martindurant** [comment]
We decided, along with other dask projects, that we could not faithfully maintain semantic versioning - given the large API and backends supported, there would, generally, always be *some* part of the code-base that could be considered not backward compatible on every release. `fsspec` is strange as a package, being both an end-user library (with a fairly stable API) and many internal details which other packages depend on in detail.

**Comment by docktermj** [comment]
@martindurant I do thank you for considering Semantic Versioning.
