### ISSUE TITLE
Disallowing ListObjectsV2 at the root of the bucket makes s3fs attempt to create a bucket

### ISSUE THREAD

**Issue by orf** [dask/s3fs#532]
**What happened**:

It's not uncommon to have a bucket that disallows listing the root, but allows listing a specific prefix. In this case `s3fs` will fail any writes and will attempt to create the bucket, which often fails with a completely different error. 

**What you expected to happen**:

Falling back to creating a bucket is very strange behaviour. I imagine it's legacy and impossible to change, but I would expect that `s3fs` does not require full list objects permissions over the bucket to perform any writes.

**Minimal Complete Verifiable Example**:

```python
In [1]: import s3fs

In [2]: s3 = s3fs.S3FileSystem(anon=False)

In [5]: s3.mkdirs("s3://s3fs-test-bucket-123/foo/bar")
2021-09-17 17:34:50,222 - s3fs - DEBUG - _call_s3 -- CALL: list_objects_v2 - () - {'MaxKeys': 1, 'Bucket': 's3fs-test-bucket-123'}
2021-09-17 17:34:50,516 - s3fs - DEBUG - _call_s3 -- Nonretryable error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
2021-09-17 17:34:50,516 - s3fs - DEBUG - _call_s3 -- CALL: create_bucket - () - {'Bucket': 's3fs-test-bucket-123', 'ACL': ''}
2021-09-17 17:34:50,576 - s3fs - DEBUG - _call_s3 -- Nonretryable error: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

The full traceback is like so:

```
File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/dask/dataframe/io/parquet/arrow.py", line 819, in initialize_write
    fs.mkdirs(path, exist_ok=True)
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/fsspec/spec.py", line 1159, in mkdirs
    return self.makedirs(path, exist_ok=exist_ok)
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/s3fs/core.py", line 731, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/app/.cache/pypoetry/virtualenvs/x/lib/python3.9/site-packages/s3fs/core.py", line 716, in _mkdir
    await self._call_s3("create_bucket", **params)
```

It seems like it's failing to detect [the bucket exists on this line](https://github.com/dask/s3fs/blob/9e7ea3784cffc4cbec05281e2a689ae4c3ff8517/s3fs/core.py#L833-L836). There are much better methods to detect if a bucket exists, like `get-bucket-location`.

**Comment by martindurant** [comment]
cc @isidentical 

Would be happy to see different techniques to determine if a bucket exists, but I would note that listing a bucket's contents might be allowed but getting its details not allowed. The AWS permissions model is complex!

Also note that `mkdirs` doesn't do anything except create a bucket (because S3 has no folders).

**Comment by orf** [comment]
For anyone else reading this, you can get around this with a specific bucket condition like so:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::s3fs-test-bucket-123",
            "Condition": {
                "NumericNotEquals": {
                    "s3:max-keys": "1"
                },
                "StringNotEquals": {
                    "s3:delimiter": ""
                }
            }
        }
    ]
}
```

But this sucks, as you are basically giving complete list access (albeit 1 key at a time!)

**Comment by orf** [comment]
> cc @isidentical
> 
> Would be happy to see different techniques to determine if a bucket exists, but I would note that listing a bucket's contents might be allowed but getting its details not allowed. The AWS permissions model is complex!
> 
> Also note that `mkdirs` doesn't do anything except create a bucket (because S3 has no folders).

In the PR I made we can call `get-bucket-location` before falling back to the existing implementation. Unfortunately `head-bucket` needs `list_objects` permission.

However... why don't we use `MaxKeys=0` as well? This works:
```
In [14]: c.list_objects_v2(Bucket="s3fs-test-bucket-123", MaxKeys=0)
Out[14]:
{'ResponseMetadata': {},
 'IsTruncated': False,
 'Name': 's3fs-test-bucket-123',
 'Prefix': '',
 'MaxKeys': 0,
 'EncodingType': 'url',
 'KeyCount': 0}
```

**Comment by martindurant** [comment]
> why don't we use MaxKeys=0 as well

I *think* this was designed for sub-directories, where we want to distinguish whether it's the actual path which exists or a sub-path. That wouldn't apply to buckets, though. So `MaxKeys` could depend on the context.

**Comment by orf** [comment]
Ok, well please let me know how I should proceed. I've got a PR and I'm willing to spend some time getting it merged as this issue is blocking some of our work. I think just calling `get-bucket-location` before `list-objects-v2` is a good compromise and should not impact anyone in any way.

**Comment by martindurant** [comment]
Well, it would add some overhead for some people. I'd appreciate if @isidentical  or maybe @mariusvniekerk has any thoughts about this.

**Comment by isidentical** [comment]
I wonder whether there is a certain endpoint which can just get back us whether the bucket exists or not, so that we don't deal with making 2 HTTP requests at the worst scenerio. I assumed it would be `HEAD_BUCKET`, but from what I see on the discussion it also needs `list_objects` permission, so not sure at that point. 

Is there any case `get-bucket-location` would return an error while the bucket exists? If not, let's just use that.

**Comment by orf** [comment]
Unfortunately `get-bucket-location` is a specific permission that needs to be added, so only using that would be a breaking change.

While this certainly adds an extra request, this does seem to be in the error-path rather than the happy-path, so it's surely not much of a big deal? And I think the results are also cached?

We could also invert the flow here: if `list-objects` fails then try `get-bucket-location`?

**Comment by martindurant** [comment]
> We could also invert the flow here: if list-objects fails then try get-bucket-location?

That would certainly be the smaller change. I have no idea which permission is more likely to be present.

**Comment by orf** [comment]
I've inverted the calls. I'd assume `get-bucket-location`, but it probably depends on the type of user.

**Comment by isidentical** [comment]
> While this certainly adds an extra request, this does seem to be in the error-path rather than the happy-path, so it's surely not much of a big deal?

Agree with @martindurant that it would reduce the burden, but still costful one some cases. 

>  And I think the results are also cached?

No, we don't cache the results.
