### ISSUE TITLE
** support in glob

### ISSUE THREAD

**Issue by mheilman** [dask/s3fs#54]
It'd be nice to support `**` in globs [as python 3.5 does](https://docs.python.org/3/library/glob.html#glob.glob).

This doesn't seem particularly important, especially with `walk`, but I thought I'd mention it as something that'd be nice to have.  I ran into a situation where it'd be slightly easier to use a glob with `**` than multiple `*`s or `walk`.

**Comment by martindurant** [comment]
Implemented in fsspec
