### ISSUE TITLE
Getting involved?

### ISSUE THREAD

**Issue by EdwinRor** [dask/s3fs#68]
How do I get involved with this project? I have been using it a lot lately.

**Comment by mrocklin** [comment]
Hi @EdwinRor .  I'm glad `s3fs` has been useful to you.  To be honest, I'm not sure what remains to be done with the project.  It has a fairly tight scope.  

You might take a look through the [open issues](https://github.com/dask/s3fs/issues) to see if anything catches your eye.

**Comment by EdwinRor** [comment]
Tight scope? The documentation was not really specific enough as to what or not  to expect other than file writing /moving /chmod experiences.
