### ISSUE TITLE
put method inconsistent between multiple runs

### ISSUE THREAD

**Issue by brechler** [dask/s3fs#737]
I am copying folder to S3 with s3fs.put(..., recursive=True) and I experience weird behavior. The code is:

    source_path = 'foo/bar'                # there are some <files and subfolders> inside
    target_path = 's3://my_bucket/baz'

    s3 = s3fs.S3FileSystem(anon=False)
    s3.put(source_path, target_path, recursive=True)

First time I run the command (files and S3 "folders" are created), results end up like this:

    s3://my_bucket/baz/<files and subfolders>

Second time I run the command, the result looks like this

    s3://my_bucket/baz/bar/<files and subfolders>

I can probably check existence of the "folders" before, but that does not solve the problem that I do not want to see bar in the resulting tree structure. I tried to append '/' to target_path in line with the documentation, but it did not have any effect.

**Comment by brechler** [comment]
Probably related to https://github.com/fsspec/s3fs/issues/560

**Comment by ianthomas23** [comment]
What versions of `s3fs` and `fsspec` are you using?

**Comment by brechler** [comment]
s3fs==2023.5.0
fsspec==2023.5.0
