### ISSUE TITLE
Allowing S3Filesystem to handle an s3 object for custom s3 configs

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/s3fs#74]
We have an s3-like server that is hosted on a service other than amazon. We need to change the 'endpoint_url' param. We are pretty comfortable using Boto and would like S3FS to simply work within that configuration. I imagine an initialization like the following:  #@

`session = boto3.Session(profile_name='my_profile')`

`s3 = session.client('s3', endpoint_url='https://some_unique_endpoint.org')`

`s3_filesys = S3FileSystem(s3)`

**Comment by mrocklin** [comment]
Have you taken a look at the code to `S3FileSystem.connect`?

```python
    def connect(self, refresh=False):
        """
        Establish S3 connection object.

        Parameters
        ----------
        refresh : bool (True)
            Whether to use cached filelists, if already read
        """
        anon, key, secret, kwargs, ckwargs, token, ssl = \
              (self.anon, self.key, self.secret, self.kwargs,
               self.client_kwargs, self.token, self.use_ssl)

        # Include the current PID in the connection key so that different
        # SSL connections are made for each process.
        tok = tokenize(anon, key, secret, kwargs, ckwargs, token,
                       ssl, os.getpid())
        if refresh:
            self._conn.pop(tok, None)
        logger.debug("Open S3 connection.  Anonymous: %s", self.anon)
        if self.anon:
            # TODO: test addition of kwargs (e.g., S3 data centre)
            from botocore import UNSIGNED
            conf = Config(connect_timeout=self.connect_timeout,
                          read_timeout=self.read_timeout,
                          signature_version=UNSIGNED)
            self.session = boto3.Session(**self.kwargs)
        else:
            conf = Config(connect_timeout=self.connect_timeout,
                          read_timeout=self.read_timeout)
            self.session = boto3.Session(self.key, self.secret, self.token,
                                         **self.kwargs)
        if tok not in self._conn:
            s3 = self.session.client('s3', config=conf, use_ssl=ssl,
                                     **self.client_kwargs)
            self._conn[tok] = s3
        return self._conn[tok]
```

It might be that what you want to do is pretty doable with modest changes (or perhaps even no changes?)  A contribution that allowed this would be very welcome.

**Comment by jreback** [comment]
https://github.com/dask/s3fs/pull/69

this exactly the use case (see the tests for an example)

**Comment by jgerardsimcock** [comment]
`TypeError: __init__() got an unexpected keyword argument 'client_kwargs'`

**Comment by jreback** [comment]
you need to clone and install
this is in master but not released

**Comment by jreback** [comment]
@martindurant could do a release at some point

**Comment by jgerardsimcock** [comment]
Yes. I went through that as well. In my source code, I have that as an option but still getting this error.

**Comment by jgerardsimcock** [comment]
Here is my init:

`def __init__(self, anon=False, key=None, secret=None, token=None,
                 use_ssl=True, client_kwargs=None, **kwargs):
        self.anon = anon
        self.key = key
        self.secret = secret
        self.token = token
        self.kwargs = kwargs

        if client_kwargs is None:
            client_kwargs = {}
        self.client_kwargs = client_kwargs
        self.dirs = {}
        self.use_ssl = use_ssl
        self.s3 = self.connect()
        S3FileSystem._singleton[0] = self`

**Comment by jgerardsimcock** [comment]
Thank you. This has been resolved.
