### ISSUE TITLE
Support Google Cloud Storage

### ISSUE THREAD

**Issue by mrocklin** [dask/s3fs#76]
Boto3 and Google Cloud Storage have an unfortunate history of not working together.  This is unfortunate, because I'd really like to use Dask on Google hardware and this seems like it would be the cheapest way to do it.

There is a *somewhat* promising stackoverflow answer here: http://stackoverflow.com/questions/34089858/copy-file-from-gcs-to-s3-in-boto3 (see the final edit of the first answer).  This, combined with https://github.com/dask/s3fs/pull/69 , might provide a solution?

cc @quasiben

**Comment by martindurant** [comment]
May be coming to https://github.com/martindurant/gcsfs/ when I get the time.
