### ISSUE TITLE
Confused about using s3fs asynchronously

### ISSUE THREAD

**Issue by pb222xd** [dask/s3fs#843]
After reading s3fs' documentation on asynchronous development https://s3fs.readthedocs.io/en/latest/#async, I tried a lot but only the following code seems to work
```python
import asyncio
from s3fs import S3FileSystem


async def main():
    s3 = S3FileSystem(key="sA3HIztxVB31tvWV9uQv",
                      secret="up8OZN7yje6I4HK6seNkXfccdSzmQA86PudmkfpR",
                      client_kwargs={'endpoint_url': "http://127.0.0.1:9000",
                                     'region_name': "auto"})
    session = await s3.set_session()
    # noinspection PyProtectedMember
    await s3._put("test.txt", "test2.txt")  # pylint: disable=protected-access
    await session.close()


if __name__ == '__main__':
    asyncio.run(main())
```
Is there any potential problem with my implementation? Thank you very much.

**Comment by martindurant** [comment]
Your implementation looks good.

**Comment by martindurant** [comment]
You mean omitting `await self.session.close()` ? This should ideally happen automatically for you when the instance gets cleaned up, but because that can happen in any thread and potentially at interpreter shutdown time, you may see (harmless) warnings about unclosed sockets and not run coroutines.

**Comment by martindurant** [comment]
Correct, if you don't want to manage instances yourself, you can reuse them. fsspec caches all instances unless explicitly avoided (such as `skip_instance_cache=True`), so if you use the same init arguments, you get exactly the same object back, and can expect the connection pool etc to still be there. It's up to you whether you want to use the context formalism for state hygene or not.
