### ISSUE TITLE
Cannot find any bucket or file in S3

### ISSUE THREAD

**Issue by katsou55** [dask/s3fs#87]
`s3 = s3fs.S3FileSystem(key=ACCESS_KEY, secret=SECRET_KEY)`
I cannot check for any file using the following methods:
`s3.cat(path='s3://test/test.txt')`
`s3.ls(path='test/')`
`s3.ls(path='test')`

> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-81-94aa9b4ccdc0> in <module>()
> ----> 1 s3.cat(path='s3://mariont-test/test.txt')
> 
> /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in cat(self, path)
>     527     def cat(self, path):
>     528         """ Returns contents of file """
> --> 529         with self.open(path, 'rb') as f:
>     530             return f.read()
>     531 
> 
> /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in open(self, path, mode, block_size, acl, fill_cache)
>     256                                       " and manage bytes" % (mode[0] + 'b'))
>     257         return S3File(self, path, mode, block_size=block_size, acl=acl,
> --> 258                       fill_cache=fill_cache)
>     259 
>     260     def _lsdir(self, path, refresh=False):
> 
> /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in __init__(self, s3, path, mode, block_size, acl, fill_cache)
>     853         else:
>     854             try:
> --> 855                 self.size = self.info()['Size']
>     856             except (ClientError, ParamValidationError):
>     857                 raise IOError("File not accessible", path)
> 
> /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in info(self)
>     859     def info(self):
>     860         """ File information about this path """
> --> 861         return self.s3.info(self.path)
>     862 
>     863     def metadata(self, refresh=False):
> 
> /Users/carlosrodrigues/anaconda/envs/testenv/lib/python2.7/site-packages/s3fs/core.pyc in info(self, path, refresh)
>     363                 return out
>     364             except (ClientError, ParamValidationError):
> --> 365                 raise FileNotFoundError(path)
>     366 
>     367     _metadata_cache = {}
> 
> FileNotFoundError: mariont-test/test.txt

Every method I call end up here. Any suggestion how to fix it ? 
(ps: I can connect to s3 with boto3.client and put files for example. So it is a bit strange)

**Comment by martindurant** [comment]
(I notice that you have `'s3://mariont-test/test.txt'` in your traceback but `'s3://test/test.txt'` in your code; I assume the latter is the real one)

When connecting with boto3.client, you use the same keys? You can do `s3.ls()` to see what buckets are associated with your user. You should check the access permissions on the bucket and key according to the AWS S3 console.

**Comment by katsou55** [comment]
'mariont-test/test.txt' is the true path. The other path I was just trying to anonymize the bucket name when I opened this issue

```
import s3fs
s3 = s3fs.S3FileSystem(key=ACCESS_KEY, secret=SECRET_KEY)
s3.ls()
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-82-d090b78b2a60> in <module>()
> ----> 1 s3.ls()
> 
> TypeError: ls() takes at least 2 arguments (1 given)


The access and secret keys are correct since I am using them on boto3 on the same notebook and it works. I also tried to open the permissions on the s3 bucket and tried to access it with anoun=True but I end up always with the same error in previous comment.

**Comment by martindurant** [comment]
Sorry, should have been `ls('')`. Also, can you try your ls cals above with `refresh=True`?

**Comment by katsou55** [comment]
Hi, sorry for the trouble. The mistake was fully mine! I used specific bucket keys instead of the user keys.
Keep going with the great work! Cheers
