### ISSUE TITLE
Implement server-side encryption

### ISSUE THREAD

**Issue by martindurant** [dask/s3fs#89]
See http://stackoverflow.com/questions/43359943/dask-dataframes-to-parquet-support-server-side-encryption

Any number of "file parameters" could be included in the constructor, for use in open() and other methods by default within the instance, but over-ridable in the call; or there could be just the specific SSE-related ones.

**Comment by dan-coates** [comment]
+1, I just ran into this in a case where I wanted to use s3fs for writing a simple file to S3 but SSE is required in my bucket...

Seems like the `open` method would be a natural place to place that kwarg.

**Comment by martindurant** [comment]
@dan-coates , would you like to experiment with #90, to see if it meets your needs? That code touches quite a few parts, and I haven't had the chance yet to trial it.

**Comment by dan-coates** [comment]
I looked through the code a bit - I'm not sure how much I like the idea of cramming everything into the `S3FileSystem` constructor and filtering things down into all the methods in the background. This isn't a use case I have right now, so this may be unnecessarily hypothetical, but what if I want to write some files that are encrypted and some that aren't, or read different files encrypted with different keys? Then I have to create multiple `S3FileSystem` objects and keep track of that.

Now, maybe that's actually easier than appending additional kwargs onto the methods where I want to open the files and whatnot, I don't know. It just seems like more of a file-level option than a global filesystem option.

I also feel like it makes the internals more convoluted with all the `self._call_s3` indirection, but I probably shouldn't throw stones there unless I'm willing to try a better implementation. :)

**Comment by martindurant** [comment]
@dan-coates , I tend to agree with you, and started to code out simply adding **kwargs to all methods that call s3 and as an instance variable on S3Files. However, we get into trouble for users accessing s3 via dask: they only have a route to provide arguments to the FileSystem constructor (with `storage_options=`), not to the individual open calls.

**Comment by dan-coates** [comment]
Yeah, I had a feeling approaching this would get down the rabbit hole of how Dask uses the package. Not having looked at how Dask uses s3fs, couldn't it bear the responsibility of filtering options down to the methods that need them? It seems wrong to tailor what is effectively a general purpose tool to a specific use case in a way that's not intuitive for the general case.

Again, just my opinion - I would like to be able to spend some time on this but don't know if I'll get the chance...

**Comment by martindurant** [comment]
I think we can safely agree that a general way to include over-ride kwargs passed to s3 calls should exist on open and other file-system methods, and I think all that dask would need is the ability to specify those arguments just once up front in the constructor. #90 should get us there, even if the code (and documentation) gets a little messy.
