### ISSUE TITLE
S3FileSystem server side encryption not supported

### ISSUE THREAD

**Issue by tomlaube** [dask/s3fs#95]
The passing of argument s3_additional_kw according to documentation like:

s3 = s3fs.S3FileSystem(s3_additional_kwargs={'ServerSideEncryption': 'AES256'})

is not valid. Server side encryption need to be part of botocore.config for the s3 client client like so:

sess = boto3.Session()
conf =  botocore.config.Config(s3={'ServerSideEncryption': "AES256"})
client = sess.client('s3', config=conf)

**Comment by tomlaube** [comment]
Is fixed with 0.1.0 config_kwargs argument

**Comment by martindurant** [comment]
OK, thanks.
