### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by mariusvniekerk** [dask/s3fs#96]
Can we cut a release with the serverside encryption params?

**Comment by martindurant** [comment]
Yes, I'll get on it. Doing releases this week ( https://github.com/conda-forge/fastparquet-feedstock/pull/8 )

**Comment by martindurant** [comment]
https://github.com/conda-forge/s3fs-feedstock/pull/11

**Comment by mariusvniekerk** [comment]
Thanks!
